Repository Flank/flank, pull requests merged in 2020-10, with the labels that each got.

#1171 feat: Dump shards and upload on every run
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/json/MatrixMapTest.kt
Labels: Tiger 🐯

#1181 docs: Investigation incorrect outcome for flaky tests
  docs/bugs/914_falsy_positive_outcome_for_flaky_tests.md
Labels: Tiger 🐯

#1188 fix: Revert "feat: Dump shards and upload on every run (#1171)"
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Labels: Snake 🐍

#1190 docs: Added documentation about Cucumber support
  README.md
  docs/cucumber_support.md
Labels: Tiger 🐯

#1210 ci: Enable RC versions for gradle (dependency update task)
  docs/dependencies_update_process.md
  flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/DependencyExtensions.kt
  flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/UpdateGradle.kt
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/DependencyExtensionsTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateGradleTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/testfiles/expected_gradle-wrapper.properties_RC.test
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/testfiles/report.json
Labels: Snake 🐍

#1175 feat: Android integration tests run on non wsl windows
  .github/workflows/windows-non-wsl-workflow.yml
  integration_tests/src/test/kotlin/utils/CommandHelper.kt
  test_runner/bash/update_flank.bat
  test_runner/build.gradle.kts
Labels: Tiger 🐯

#1214 feat: Added printing missing options
  README.md
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateGradleTest.kt
  test_runner/flank.ios.yml
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: Snake 🐍

#1215 docs: Added documentation about missing options
  README.md
  test_runner/flank.yml
Labels: Snake 🐍

#1186 feat: Grant permissions addition
  README.md
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/config/FlankDefaults.kt
  test_runner/src/main/kotlin/ftl/config/Load.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ipblocks/IPBlocksListCommandTest.kt
Labels: Tiger 🐯

#1148 ci: Add scripts for test artifacts managment
  .env
  .github/workflows/flank-scripts-macos_workflow.yml
  .github/workflows/integration_tests.yml
  .github/workflows/macos_workflow.yml
  .github/workflows/ubuntu-workflow.yml
  .github/workflows/windows-non-wsl-workflow.yml
  .github/workflows/wsl-workflow.yml
  .gitignore
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  docs/test_artifacts.md
  flank-scripts/README.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/Main.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/TestArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/ArtifactsArchive.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/Constants.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/Context.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/DownloadFixtures.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/IsNewVersionAvailable.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/LinkArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/PrepareTestArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/RemoveRemoteCopy.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/ResolveArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/TestArtifactsRepo.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/UploadFixtures.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/ZipArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/Download.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/Env.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/File.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/Git.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/Net.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/ShellExecute.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/Zip.kt
  flank-scripts/src/test/kotlin/flank/scripts/testartifacts/TestArtifactsUtils.kt
  flank-scripts/src/test/kotlin/flank/scripts/testartifacts/core/ArtifactsArchiveTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/testartifacts/core/PrepareTestArtifactsKtTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/testartifacts/core/ZipTestArtifactsKt.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/FileKtTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/ZipKtTest.kt
  gradle.properties
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/mock/MockServer.kt
  test_runner/src/main/kotlin/ftl/mock/TestArtifact.kt
  test_runner/src/test/kotlin/ftl/ios/Constants.kt
  test_runner/src/test/kotlin/ftl/ios/ParseTest.kt
  test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt
Labels: Tiger 🐯

#1236 fix: Empty branch name in workflows
  .github/workflows/integration_tests.yml
  .github/workflows/windows-non-wsl-workflow.yml
  .github/workflows/wsl-workflow.yml
Labels: Tiger 🐯

#1230 feat: Add type
  README.md
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/Type.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Labels: New Option, Tiger 🐯

#1222 docs: Add flank website code
  .github/workflows/website.yml
  README.md
  docs/assets/bugsnag-logo-dark.png
  docs/assets/logo.png
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
  requirements.txt
Labels: Tiger 🐯

#1243 fix: Disable cache for :test_runner:shadowJar task
  test_runner/build.gradle.kts
Labels: Snake 🐍

#1247 fix: Flank web documentation link
  README.md
Labels: Snake 🐍

#1238 feat: Scenario Labels
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Labels: New Option, Tiger 🐯

#1244 feat: Added scenario-numbers
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Labels: New Option, Tiger 🐯

#1256 feat: Update test shard limits
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
Labels: Snake 🐍

#1255 feat: Obb file addition
  docs/index.md
  test_projects/android/gameloop/test.obb
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Labels: New Option, Tiger 🐯

#1261 fix: Add additional index to matrix when multiple test runs
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt
Labels: Tiger 🐯

#1267 feat: Add Other Files for iOS
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/android/Utils.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadOtherFiles.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
Labels: New Option, Tiger 🐯, iOS

#1219 fix: #842 support for test targets flag in multiple testbundles xctest
  .gitignore
  test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/project.pbxproj
  test_projects/ios/EarlGreyExample/EarlGreyExampleSwiftTests/EarlGrey.swift
  test_projects/ios/EarlGreyExample/ops.sh
  test_projects/ios/FlankExample/FlankExample.xcodeproj/project.pbxproj
  test_projects/ios/FlankExample/FlankExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  test_projects/ios/FlankExample/FlankExample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  test_projects/ios/FlankExample/FlankExample.xcodeproj/xcshareddata/xcschemes/FlankExample.xcscheme
  test_projects/ios/FlankExample/FlankExample.xcodeproj/xcshareddata/xcschemes/FlankTests.xcscheme
  test_projects/ios/FlankExample/FlankExample.xcodeproj/xcuserdata/zuziakaxel.xcuserdatad/xcschemes/xcschememanagement.plist
  test_projects/ios/FlankExample/FlankExample/AppDelegate.swift
  test_projects/ios/FlankExample/FlankExample/Assets.xcassets/AppIcon.appiconset/Contents.json
  test_projects/ios/FlankExample/FlankExample/Assets.xcassets/Contents.json
  test_projects/ios/FlankExample/FlankExample/Base.lproj/LaunchScreen.storyboard
  test_projects/ios/FlankExample/FlankExample/Base.lproj/Main.storyboard
  test_projects/ios/FlankExample/FlankExample/Info.plist
  test_projects/ios/FlankExample/FlankExample/SceneDelegate.swift
  test_projects/ios/FlankExample/FlankExample/ViewController.swift
  test_projects/ios/FlankExample/FlankExampleSecondTests/FlankExampleSecondTests.swift
  test_projects/ios/FlankExample/FlankExampleSecondTests/Info.plist
  test_projects/ios/FlankExample/FlankExampleTests/FlankExampleTests.swift
  test_projects/ios/FlankExample/FlankExampleTests/Info.plist
  test_projects/ios/FlankExample/ops.sh
  test_projects/ops.sh
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/ios/Constants.kt
  test_runner/src/test/kotlin/ftl/ios/ParseTest.kt
  test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt
Labels: Bug, iOS

#1273 feat: Add Additional Ipas option to iOS
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/config/ios/IosGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/android/Utils.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
Labels: New Option, Tiger 🐯, iOS

#1274 test: Disable iOS test for Windows
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt
Labels: Snake 🐍

#1269 ci: Add build scan for ubuntu workflow
  .github/workflows/ubuntu-workflow.yml
  firebase_apis/test_api/build.gradle.kts
  integration_tests/build.gradle.kts
  settings.gradle.kts
  test_runner/build.gradle.kts
Labels: Tiger 🐯

#1283 fix: Integration tests on windows
  .github/workflows/integration_tests.yml
  docs/windows_and_github_actions.md
  test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
Labels: Tiger 🐯

#1286 ci: Update existing bot comment
  .github/workflows/ubuntu-workflow.yml
Labels: Tiger 🐯

#1284 feat: Add Type to iOS
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/Type.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/yml/TypeTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Labels: New Option, Tiger 🐯, iOS
