Repository Flank/flank, pull requests merged in 2020-11, with the labels that each got.

#1287 feat: ios scenario numbers
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: New Option

#1266 feat: iOS add directories-to-pull
  docs/index.md
  test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/project.pbxproj
  test_projects/ios/EarlGreyExample/EarlGreyExampleSwift/ViewController.swift
  test_projects/ios/FlankExample/FlankExample/ViewController.swift
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/android/Utils.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
Labels: New Option, Tiger 🐯, iOS

#1291 feat: Add --test-special-entitlements for iOS
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/config/ios/IosGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Labels: New Option, Tiger 🐯, iOS

#1289 feat: add ios app for gameloop
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/config/ios/IosGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: New Option, Tiger 🐯

#1301 fix: Handling broken token issues
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/config/Credentials.kt
  test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/gc/GcTesting.kt
  test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
  test_runner/src/main/kotlin/ftl/gc/UserAuth.kt
  test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
  test_runner/src/main/kotlin/ftl/run/exception/FlankException.kt
  test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
  test_runner/src/test/kotlin/ftl/gc/UserAuthTest.kt
Labels: Tiger 🐯

#1292 feat: Added Performance Metrics for Android
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
  test_runner/src/main/kotlin/ftl/mock/MockServer.kt
  test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
  test_runner/src/main/kotlin/ftl/reports/api/ProcessFromApi.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
  test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
  test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Labels: Android, Feature, Tiger 🐯

#1311 docs: Update documentations & Add Headings
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/flank.yml
Labels: Documentation

#1307 fix: Integration tests on windows
  flank-scripts/bash/buildFlankScripts.bat
  flank-scripts/bash/flankScripts.bat
  test_runner/src/main/kotlin/ftl/gc/UserAuth.kt
  test_runner/src/test/kotlin/ftl/run/status/MultiLinePrinterTest.kt
Labels: Tiger 🐯

#1323 fix: Nested subdirectories in results-dir
  test_runner/src/main/kotlin/ftl/util/MatrixUtil.kt
  test_runner/src/test/kotlin/ftl/util/MatrixUtilTest.kt
Labels: Bug

#1326 fix: Downloading performance Metrics
  integration_tests/src/test/kotlin/utils/TestsConsts.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
  test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
  test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
Labels: Bug

#1299 feat: add test targets for shard
  .github/workflows/integration_tests.yml
  docs/index.md
  flank-scripts/src/test/kotlin/flank/scripts/utils/FileKtTest.kt
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/filter/TestFilters.kt
  test_runner/src/main/kotlin/ftl/gc/android/CreateAndroidInstrumentationTest.kt
  test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/AndroidTestConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateInstrumentationConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
  test_runner/src/main/kotlin/ftl/shard/Shard.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-shards-simple.yml
  test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/gc/android/CreateAndroidInstrumentationTestTest.kt
  test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
Labels: Android, Feature, New Option, Tiger 🐯

#1281 refactor: Prepare flank codebase for supporting iOS testplans
  docs/feature/ios_test_plans.md
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/ios/Parse.kt
  test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/FindXcTestNamesV1.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/FindXcTestNamesV2.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/RewriteXcTestRunV1.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/RewriteXcTestRunV2.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/FindTestsForTarget.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseObjTests.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseSwiftTests.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/Util.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/test/kotlin/ftl/fixtures/ios_test_plan.yml
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/ios/Constants.kt
  test_runner/src/test/kotlin/ftl/ios/ParseTest.kt
  test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/FindXcTestNamesV1KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/FindXcTestNamesV2KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/RewriteXcTestRunV1KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/RewriteXcTestRunV2KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/Util.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/common/FindTestsForTargetKtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/common/ParseObjTestsKtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/common/ParseSwiftTestsKtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/common/UtilKtTest.kt
Labels: Feature, New Option, Tiger 🐯, iOS

#1329 fix: Uploading performance metrics for multiple matrices
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
  test_runner/src/main/kotlin/ftl/util/ProgressBar.kt
  test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
  test_runner/src/test/kotlin/ftl/util/ProgressBarTest.kt
Labels: Bug

#1338 fix: Fix printing supported versions id
  test_runner/src/main/kotlin/ftl/android/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: Tiger 🐯

#1310 ci: Copy properties from issue to pull request
  .github/workflows/pr_checks.yml
  flank-scripts/README.md
  flank-scripts/src/main/kotlin/flank/scripts/Main.kt
  flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GenerateChangeLog.kt
  flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GithubPullRequest.kt
  flank-scripts/src/main/kotlin/flank/scripts/exceptions/FlankScriptsExceptions.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubPullRequest.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/FindReferenceIssue.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/GitHubIssuePropertiesCopy.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/PullRequestCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/SetAssignees.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/SetLabels.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/ZenHubCopyEstimations.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/ZenHubIssue.kt
  flank-scripts/src/test/kotlin/flank/scripts/FuelMockServer.kt
  flank-scripts/src/test/kotlin/flank/scripts/FuelTestRunner.kt
  flank-scripts/src/test/kotlin/flank/scripts/GithubMockServerHandler.kt
  flank-scripts/src/test/kotlin/flank/scripts/ZenHubMockServerHandler.kt
  flank-scripts/src/test/kotlin/flank/scripts/github/GithubApiTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/pullrequest/FindReferenceIssueTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/pullrequest/SetAssigneesTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/pullrequest/SetLabelsTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/pullrequest/ZenHubCopyEstimationsTest.kt
Labels: Feature, Tiger 🐯

#1339 refactor: Simplify beforeRunTests return singature
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/run/DumpShards.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
  test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
  test_runner/src/main/kotlin/ftl/run/common/UpdateMatrixFile.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadOtherFiles.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunMessage.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunTests.kt
  test_runner/src/main/kotlin/ftl/util/FileReference.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
  test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
  test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt
Labels: Refactor, Snake 🐍

#1325 feat: IOS GameLoop addition
  test_projects/ios/FlankGameLoopExample/FlankGameLoopExample.xcodeproj/project.pbxproj
  test_projects/ios/FlankGameLoopExample/FlankGameLoopExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  test_projects/ios/FlankGameLoopExample/FlankGameLoopExample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  test_projects/ios/FlankGameLoopExample/FlankGameLoopExample.xcodeproj/xcshareddata/xcschemes/FlankGameLoopExample.xcscheme
  test_projects/ios/FlankGameLoopExample/exportOptions.plist
  test_projects/ios/FlankGameLoopExample/flankgameloop/Actions.sks
  test_projects/ios/FlankGameLoopExample/flankgameloop/AppDelegate.swift
  test_projects/ios/FlankGameLoopExample/flankgameloop/Assets.xcassets/AccentColor.colorset/Contents.json
  test_projects/ios/FlankGameLoopExample/flankgameloop/Assets.xcassets/AppIcon.appiconset/Contents.json
  test_projects/ios/FlankGameLoopExample/flankgameloop/Assets.xcassets/Contents.json
  test_projects/ios/FlankGameLoopExample/flankgameloop/Base.lproj/Main.storyboard
  test_projects/ios/FlankGameLoopExample/flankgameloop/FTLGameLoop.swift
  test_projects/ios/FlankGameLoopExample/flankgameloop/GameScene.sks
  test_projects/ios/FlankGameLoopExample/flankgameloop/GameScene.swift
  test_projects/ios/FlankGameLoopExample/flankgameloop/GameViewController.swift
  test_projects/ios/FlankGameLoopExample/flankgameloop/Info.plist
  test_projects/ios/FlankGameLoopExample/ipa/DistributionSummary.plist
  test_projects/ios/FlankGameLoopExample/ipa/ExportOptions.plist
  test_projects/ios/FlankGameLoopExample/ipa/FlankGameLoopExample.ipa
  test_projects/ios/FlankGameLoopExample/ipa/Packaging.log
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-gameloop-ios.yml
Labels: New Option, iOS

#1355 docs: Add documentation about code review by step
  docs/onboarding/5_code_review.md
  mkdocs.yml
Labels: Documentation

#1357 fix: Fix release Action
  .github/workflows/release.yml
  flank-actions/Dockerfile
  flank-actions/sendMessage
Labels: Bug, release

#1352 ci: Make flank release more automatically
  .github/workflows/create_new_release.yml
  .github/workflows/release_notes_generation.yml
  docs/release_process.md
Labels: Feature, Tiger 🐯
