Repository Flank/flank, pull requests merged in 2020-04, with the labels that each got.

#693 Add logic to prevent fetching from invalid test matrices
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/main/kotlin/ftl/util/MatrixState.kt
  test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
Labels: 3, Tech Debt

#700 Add exponential backoff
  test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
Labels: 3

#704 Fix shards calculation when there are ignored tests and shardTime is -1
  release_notes.md
  test_runner/src/main/kotlin/ftl/shard/Shard.kt
  test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Labels: bug

#696 Introduce global exception handler
  README.md
  test_runner/src/main/kotlin/ftl/Main.kt
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/AndroidTestShard.kt
  test_runner/src/main/kotlin/ftl/args/ArgsFileVisitor.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/YamlDeprecated.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/CommandUtil.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
  test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/json/MatrixMap.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
  test_runner/src/main/kotlin/ftl/run/common/GetLastArgs.kt
  test_runner/src/main/kotlin/ftl/run/common/GetLastMatrices.kt
  test_runner/src/main/kotlin/ftl/shard/Shard.kt
  test_runner/src/main/kotlin/ftl/util/FlankException.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperFilePathTest.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/RefreshCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidDoctorCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosDoctorCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
  test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
  test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Labels: 5, Tech Debt

#708 Add ignore failed tests option to Flank
  README.md
  release_notes.md
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt
  test_runner/src/main/kotlin/ftl/json/MatrixMap.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/main/kotlin/ftl/util/FlankException.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Labels: 3, Feature, Feedback Wanted

#711 Remove hardcoded height
  junit_html_report/src/App.css
  junit_html_report/src/index.css
  release_notes.md
  test_runner/src/main/resources/inline.html
Labels: bug

#712 Add keep file path for ios
  README.md
  release_notes.md
  test_runner/flank.ios.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/AndroidFlankYml.kt
  test_runner/src/main/kotlin/ftl/args/yml/FlankYml.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
Labels: 8, bug, iOS

#714 Add support for num-uniform-shards option
  release_notes.md
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/AndroidTestShard.kt
  test_runner/src/main/kotlin/ftl/args/yml/AndroidGcloudYml.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/Utils.kt
  test_runner/src/main/kotlin/ftl/reports/api/CreateTestExecutionData.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/gc/UtilsKtTest.kt
  test_runner/src/test/kotlin/ftl/reports/api/CreateTestExecutionDataKtTest.kt
Labels: Feature

#709 Add support for robo-directives & robo-script options
  README.md
  release_notes.md
  test_app/app/src/androidTest/java/com/example/test_app/BaseInstrumentedTest.kt
  test_app/app/src/main/java/com/example/test_app/MainActivity.kt
  test_app/app/src/main/res/layout/activity_main.xml
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/AndroidFlankYml.kt
  test_runner/src/main/kotlin/ftl/args/yml/AndroidGcloudYml.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/config/FlankRoboDirective.kt
  test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/Utils.kt
  test_runner/src/main/kotlin/ftl/gc/android/CreateAndroidInstrumentationTest.kt
  test_runner/src/main/kotlin/ftl/gc/android/CreateAndroidRobotTest.kt
  test_runner/src/main/kotlin/ftl/gc/android/SetupAndroidTest.kt
  test_runner/src/main/kotlin/ftl/gc/android/Utils.kt
  test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
  test_runner/src/main/kotlin/ftl/reports/api/CreateJUnitTestSuite.kt
  test_runner/src/main/kotlin/ftl/reports/api/CreateTestSuitOverviewData.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/AndroidTestConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateInstrumentationConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateRoboConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadOtherFiles.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/.gitignore
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/MainActivity_robo_script.json
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-robo.yml
  test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/gc/android/CreateAndroidInstrumentationTestTest.kt
Labels: Feature

#731 730 - Refactor jUnit HTML report
  junit_html_report/.editorconfig
  junit_html_report/.gitignore
  junit_html_report/README.md
  junit_html_report/index.ejs
  junit_html_report/inline.js
  junit_html_report/package-lock.json
  junit_html_report/package.json
  junit_html_report/public/favicon.ico
  junit_html_report/public/index.html
  junit_html_report/public/manifest.json
  junit_html_report/src/App.css
  junit_html_report/src/App.test.tsx
  junit_html_report/src/App.tsx
  junit_html_report/src/components/group.ts
  junit_html_report/src/data.tsx
  junit_html_report/src/helpers.ts
  junit_html_report/src/index.css
  junit_html_report/src/index.ts
  junit_html_report/src/index.tsx
  junit_html_report/src/logo.svg
  junit_html_report/src/react-app-env.d.ts
  junit_html_report/src/serviceWorker.js
  junit_html_report/src/styles.scss
  junit_html_report/src/types/index.ts
  junit_html_report/tsconfig.json
  junit_html_report/update_report.sh
  junit_html_report/webpack.config.js
  junit_html_report/yarn.lock
  release_notes.md
  test_runner/src/main/kotlin/ftl/reports/CostReport.kt
  test_runner/src/main/kotlin/ftl/reports/HtmlErrorReport.kt
  test_runner/src/main/kotlin/ftl/reports/JUnitReport.kt
  test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
  test_runner/src/main/kotlin/ftl/reports/util/IReport.kt
  test_runner/src/main/resources/inline.html
  test_runner/src/test/kotlin/ftl/reports/HtmlErrorReportTest.kt
Labels: Tech Debt
