Repository Flank/flank, pull requests merged in 2020-12, with the labels that each got.

#1366 fix: Generation of release notes
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
Labels: Bug, Tiger 🐯

#1369 fix: Add fallback when cannot get reference to avoid failing tests on release
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/utils/Git.kt
Labels: Bug

#1372 fix: Fix Flank Scripts version verification tasks
  .github/workflows/release_flank_scripts.yml
  flank-scripts/README.md
  flank-scripts/bash/flankScripts.bat
  flank-scripts/build.gradle.kts
Labels: Bug, Tiger 🐯

#1380 docs: Added documentation about handling #1374 issue
  docs/bugs/1374_invalid_class
  docs/bugs/1374_invalid_class.md
Labels: Bug

#1321 feat: iOS support for testplans
  gradle.properties
  test_runner/src/main/kotlin/ftl/args/CalculateShardsResult.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/FindXcTestNamesV1.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/FindXcTestNamesV2.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/ReduceXcTestRunV1.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/ReduceXcTestRunV2.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/RewriteXcTestRunV1.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/RewriteXcTestRunV2.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/XcTestData.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/XcTestRunFlow.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/Util.kt
  test_runner/src/main/kotlin/ftl/run/DumpShards.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/shard/Chunk.kt
  test_runner/src/main/kotlin/ftl/util/FlankTestMethod.kt
  test_runner/src/main/kotlin/ftl/util/FlowExt.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsFileTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/ios_test_plan.yml
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-xctestrunv2-all.yml
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/FindXcTestNamesV1KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/FindXcTestNamesV2KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/ReduceXcTestRunV1KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/ReduceXcTestRunV2KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/RewriteXcTestRunV1KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/RewriteXcTestRunV2KtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/Util.kt
  test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
Labels: Feature, Tiger 🐯, iOS

#1378 ci: Update GH API
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GenerateChangeLog.kt
  flank-scripts/src/main/kotlin/flank/scripts/exceptions/FlankScriptsExceptionMappers.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCommit.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCreateIssue.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCreateIssueComment.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubUpdateIssue.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubWorkflowRun.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GithubPullRequest.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/FindReferenceIssue.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/SetLabels.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/Serialization.kt
  flank-scripts/src/test/kotlin/flank/scripts/GithubMockServerHandler.kt
  flank-scripts/src/test/kotlin/flank/scripts/github/GithubApiTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/pullrequest/FindReferenceIssueTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/SerializationTest.kt
Labels: Feature, Tiger 🐯

#1362 feat: Add logic to verify xml results
  integration_tests/build.gradle.kts
  integration_tests/buildSrc/src/main/kotlin/Deps.kt
  integration_tests/src/test/kotlin/IntegrationTests.kt
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  integration_tests/src/test/kotlin/integration/IntergrationTestsUtils.kt
  integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
  integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt
  integration_tests/src/test/kotlin/integration/SanityRoboIT.kt
  integration_tests/src/test/kotlin/integration/TestFilteringIT.kt
  integration_tests/src/test/kotlin/utils/LoadTestSuites.kt
  integration_tests/src/test/kotlin/utils/OutputHelper.kt
  integration_tests/src/test/kotlin/utils/TestsConsts.kt
  integration_tests/src/test/kotlin/utils/testResults/TestSuite.kt
  integration_tests/src/test/resources/cases/flank_android_run_timeout.yml
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
Labels: Feature, Tiger 🐯

#1398 ci: Add create google account config step
  .github/workflows/full_suite_integration_tests.yml
Labels: Snake 🐍

#1400 ci: Change gradle command
  .github/workflows/full_suite_integration_tests.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/integration/PrepareMessage.kt
  flank-scripts/src/test/kotlin/flank/scripts/integration/ProcessResultTest.kt
Labels: Snake 🐍

#1393 feat: upload matrix ids
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/main/kotlin/ftl/run/common/UpdateMatrixFile.kt
Labels: Feature, Tiger 🐯

#1401 docs: Update orchestrator version in docs
  docs/test_sharding.md
Labels: Bug, Snake 🐍

#1395 fix: Print args when iOS tests are not found
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
  test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
Labels: Tiger 🐯

#1405 fix: cancelCommandRuns should works independent
  test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt
Labels: Bug, Tech Debt, Tiger 🐯

#1404 feat: Add basic gameloop IT for Android
  integration_tests/src/test/kotlin/integration/GameloopIT.kt
  integration_tests/src/test/resources/cases/flank_android_gameloop_success.yml
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
Labels: Tiger 🐯

#1409 ci: trigger integration tests from pr comment
  .github/workflows/full_suite_integration_tests.yml
  integration_tests/build.gradle.kts
Labels: Feature, Tiger 🐯

#1413 fix: Fix calculate shards test
  test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Labels: Tiger 🐯

#1410 fix: Fix integration tests on CI.
  integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
Labels: Bug, IT_Failed, Tiger 🐯

#1414 fix: Add attempts to performance test
  test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Labels: Bug, Tiger 🐯

#1415 style: Change Detekt to Ktlint
  .githooks/pre-commit
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  config/detekt.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ci/nexttag/NextReleaseTagCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/AppendReleaseNotes.kt
  flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GenerateChangeLog.kt
  flank-scripts/src/main/kotlin/flank/scripts/dependencies/update/DependenciesUpdateCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/integration/Extensions.kt
  flank-scripts/src/main/kotlin/flank/scripts/integration/ProcessResultCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/integration/WorkflowSummary.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/SetLabels.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/ReleaseCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnag.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnagCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ios/IosBuildCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildAndroid.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildIosTestArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/utils/PathHelper.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/ShellExecute.kt
  flank-scripts/src/test/kotlin/flank/scripts/FuelMockServer.kt
  flank-scripts/src/test/kotlin/flank/scripts/GithubMockServerHandler.kt
  flank-scripts/src/test/kotlin/flank/scripts/ci/releasenotes/AppendReleaseNotesTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/ci/releasenotes/GenerateReleaseNotesCommandTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/DependencyExtensionsTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateDependenciesTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdateGradleTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/dependencies/update/UpdatePluginsTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/integration/ProcessResultTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/pullrequest/SetAssigneesTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/testartifacts/core/PrepareTestArtifactsKtTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/testartifacts/core/ZipTestArtifactsKt.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/SerializationTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/VersionParseTest.kt
  integration_tests/build.gradle.kts
  integration_tests/buildSrc/src/main/kotlin/Deps.kt
  integration_tests/src/test/kotlin/IntegrationTests.kt
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  integration_tests/src/test/kotlin/integration/IntergrationTestsUtils.kt
  integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
  integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt
  samples/gradle-export-api/src/main/kotlin/ftl/sample/FetchBuildData.kt
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/run/DumpShards.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/ReduceXcTestRunV1KtTest.kt
  test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
  test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
  test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Labels: Bug, Styling, Tiger 🐯

#1421 feat: Default project Id - use GOOGLE_APPLICATION_CREDENTIALS first, then GOOGLE_CLOUD_PROJECT
  docs/index.md
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
  test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
  test_runner/src/test/kotlin/ftl/args/FetchProjectIdTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
Labels: Feature, Tiger 🐯

#1424 ci: Auto update firebase api client
  .github/workflows/update_dependencies.yml
  .github/workflows/update_dependencies_and_client.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/GenerateJavaClientCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/UpdateApiJsonCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/DownloadSoftware.kt
Labels: Feature, Tiger 🐯

#1433 ci: Change IT workflow comment
  .github/workflows/full_suite_integration_tests.yml
Labels: Snake 🐍

#1432 refactor: Small changes in flank-scripts module
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/commons/LastWorkflowRunDate.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubCommit.kt
  flank-scripts/src/main/kotlin/flank/scripts/integration/WorkflowSummary.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/GitHubIssuePropertiesCopy.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/FirebaseCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/apiclient/GenerateJavaClientCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/apiclient/UpdateApiJsonCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/zenhub/ZenHubAPI.kt
  flank-scripts/src/main/kotlin/flank/scripts/zenhub/ZenHubIssue.kt
  flank-scripts/src/test/kotlin/flank/scripts/FuelMockServer.kt
  flank-scripts/src/test/kotlin/flank/scripts/GithubMockServerHandler.kt
  flank-scripts/src/test/kotlin/flank/scripts/ZenHubMockServerHandler.kt
  flank-scripts/src/test/kotlin/flank/scripts/zenhub/ZenHubCopyEstimationsTest.kt
Labels: Feature, Tiger 🐯

#1429 feat: Change uploading file output
  common/src/main/kotlin/flank.common/Strings.kt
  integration_tests/build.gradle.kts
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  integration_tests/src/test/kotlin/integration/IntergrationTestsUtils.kt
  integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
  integration_tests/src/test/resources/compare/GameloopIT-ios-compare
  integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
  test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
  test_runner/src/main/kotlin/ftl/run/DumpShards.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
  test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunMessage.kt
  test_runner/src/main/kotlin/ftl/util/ProgressBar.kt
  test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
  test_runner/src/test/kotlin/ftl/run/GenericTestRunnerTest.kt
  test_runner/src/test/kotlin/ftl/util/ProgressBarTest.kt
Labels: Feature, Tiger 🐯

#1436 feat: 1422 autodetect new gcloud features
  .github/workflows/update_dependencies_and_client.yml
  common/src/main/kotlin/flank.common/Strings.kt
  flank-scripts/README.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/FirebaseCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/CheckForSDKUpdateCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/CommitList.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/Extensions.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/LastSDKUpdateRun.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/OpenedUpdates.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/SDKUpdateContext.kt
  flank-scripts/src/main/kotlin/flank/scripts/zenhub/ZenHubAPI.kt
  flank-scripts/src/main/kotlin/flank/scripts/zenhub/objects/ConvertToEpicRequest.kt
  flank-scripts/src/test/kotlin/flank/scripts/shell/firebase/sdk/SDKUpdateTest.kt
Labels: Dragon 🐲, Feature

#1439 ci: Remove sanity checks and change full suite IT OS to macOS
  .github/workflows/full_suite_integration_tests.yml
  .github/workflows/integration_tests.yml
Labels: Snake 🐍
