Repository Flank/flank, pull requests merged in 2020-09, with the labels that each got.

#1054 fix: firebase refresh fails when test zip file doesn't exist (#1052)
  test_runner/src/main/kotlin/ftl/args/AndroidArgsCompanion.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgsCompanion.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/run/common/GetLastArgs.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: :tiger:

#1110 feat: Finialize the slack sending integration with actions
  .github/workflows/release.yml
  action.yml
Labels: Tiger :tiger:

#1111 feat: check if gcs path exist before run
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
Labels: Tiger :tiger:

#1109 feat: Integration tests for Flank
  .github/workflows/macos_workflow.yml
  .github/workflows/release.yml
  .github/workflows/ubuntu-workflow.yml
  docs/instrumentation_tests.md
  integration_tests/build.gradle.kts
  integration_tests/buildSrc/build.gradle.kts
  integration_tests/buildSrc/src/main/kotlin/Deps.kt
  integration_tests/gradle/wrapper/gradle-wrapper.jar
  integration_tests/gradle/wrapper/gradle-wrapper.properties
  integration_tests/gradlew
  integration_tests/gradlew.bat
  integration_tests/src/test/kotlin/FlankCommand.kt
  integration_tests/src/test/kotlin/IntegrationTests.kt
  integration_tests/src/test/kotlin/TestParameters.kt
  integration_tests/src/test/kotlin/utils/CommandHelper.kt
  integration_tests/src/test/kotlin/utils/ProcessResult.kt
  integration_tests/src/test/kotlin/utils/SystemProperty.kt
  integration_tests/src/test/kotlin/utils/TestsConsts.kt
  integration_tests/src/test/resources/flank_android.yml
  integration_tests/src/test/resources/flank_ios.yml
  test_runner/build.gradle.kts
  test_runner/settings.gradle.kts
Labels: Tiger :tiger:

#1121 fix: dockerfile fix for slack message send
  flank-actions/Dockerfile
Labels: Snake :snake:

#1095 ci: add new bash scripts for test artifacts generation
  .env
  docs/test_artifacts.md
  flank-scripts/bash/flankScripts
  test_projects/android/bash/generate-multi-modules-apks.sh
  test_projects/android/bash/generate_apks.sh
  test_projects/android/bash/generate_duplicated_names_apks.sh
  test_projects/android/ops.sh
  test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/project.pbxproj
  test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/xcshareddata/xcschemes/EarlGreyExampleSwiftTests.xcscheme
  test_projects/ios/EarlGreyExample/ops.sh
  test_projects/ops.sh
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-duplicated.yml
Labels: Tiger :tiger:

#1125 feat: Readded shadowjar minimization
  test_runner/build.gradle.kts
Labels: Snake :snake:

#1124 fix: Reflect gclouds outcome for robo tests
  test_runner/src/main/kotlin/ftl/json/OutcomeDetailsFormatter.kt
  test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt
  test_runner/src/main/kotlin/ftl/reports/outcome/CreateTestSuiteOverviewData.kt
  test_runner/src/main/kotlin/ftl/reports/outcome/TestOutcome.kt
  test_runner/src/main/kotlin/ftl/reports/outcome/TestOutcomeContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunMessage.kt
  test_runner/src/test/kotlin/ftl/json/OutcomeDetailsFormatterTest.kt
  test_runner/src/test/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummaryKtTest.kt
Labels: Tiger :tiger:

#1127 build: Update flank_update script
  test_runner/bash/update_flank.sh
Labels: Snake :snake:

#1129 build: Disable IT for iOS
  integration_tests/src/test/kotlin/IntegrationTests.kt
Labels: Snake :snake:

#1128 build: Enhance gradle structure
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  flank-scripts/build.gradle.kts
  integration_tests/build.gradle.kts
  samples/gradle-export-api/build.gradle.kts
  settings.gradle.kts
  test_runner/build.gradle.kts
Labels: Tiger 🐯

#1126 feat: Allow Flank using different environment variables between test-apks
  docs/using_different_environment_variables_in_different_matrices.md
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/AppTestPair.kt
  test_runner/src/main/kotlin/ftl/gc/android/SetupEnvironmentVariables.kt
  test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/AndroidTestConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateInstrumentationConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
  test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
Labels: Tiger 🐯

#1114 ci: Add Windows workflow
  .github/workflows/ubuntu-workflow.yml
  .github/workflows/windows_workflow.yml
  test_runner/.gitignore
  test_runner/build.gradle.kts
  test_runner/gradle.properties
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/doctor/Doctor.kt
  test_runner/src/main/kotlin/ftl/reports/util/MatrixPath.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperFilePathTest.kt
  test_runner/src/test/kotlin/ftl/args/yml/ErrorParserTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/RefreshCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/IPBlocksCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ipblocks/IPBlocksListCommandTest.kt
  test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
  test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
  test_runner/src/test/kotlin/ftl/reports/xml/JUnitXmlTest.kt
  test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
  test_runner/src/test/kotlin/ftl/run/status/VerbosePrinterTest.kt
  test_runner/src/test/kotlin/ftl/util/BashTest.kt
  test_runner/src/test/kotlin/ftl/util/LogTableBuilderTest.kt
Labels: Dragon 🐲

#1137 fix: Running Code coverage job
  .github/workflows/macos_workflow.yml
Labels: Snake 🐍

#1139 docs: Optimization docs addition
  README.md
  docs/building_updating_flank.md
Labels: Snake 🐍

#1141 feat: add Java 15 compile support
  .github/workflows/macos_workflow.yml
  README.md
  flank-scripts/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  test_runner/build.gradle.kts
  test_runner/gradle/wrapper/gradle-wrapper.properties
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/util/BugsnagInitHelper.kt
  test_runner/src/main/kotlin/ftl/util/Obfuscation.kt
  test_runner/src/main/kotlin/ftl/util/TestMatrixExtension.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/ftl/util/FlankBugsnagInitHelperTest.kt
Labels: Tiger 🐯

#1149 fix: Flank-scripts next release tag generation
  flank-scripts/src/main/kotlin/flank/scripts/utils/Serialization.kt
Labels: Snake 🐍

#1151 fix: update flank-scripts serialization
  flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GitHubRelease.kt
  flank-scripts/src/main/kotlin/flank/scripts/ci/releasenotes/GithubPullRequest.kt
  flank-scripts/src/main/kotlin/flank/scripts/exceptions/FlankScriptsExceptionMappers.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/BugSnagResponse.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnag.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/Serialization.kt
  flank-scripts/src/test/kotlin/flank/scripts/FuelTestRunner.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/SerializationTest.kt
Labels: Tiger 🐯

#1152 ci: added WSL workflow
  .github/workflows/windows_workflow.yml
  .github/workflows/wsl-workflow.yml
  README.md
  docs/windows_wsl_guide.md
Labels: Tiger 🐯

#1158 ci: Fix test artifacts url
  test_runner/src/main/kotlin/ftl/mock/TestArtifact.kt
Labels: Snake 🐍

#1131 docs: Investigate flank options
  docs/investigate_flank_options.md
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/IYmlKeys.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidFlankConfig.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/config/ios/IosGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
Labels: Tiger 🐯

#1164 fix: Dependabot security issues
  junit_html_report/package-lock.json
  junit_html_report/package.json
Labels: Snake 🐍

#1161 fix: release notes slack tweaks
  flank-actions/Dockerfile
  flank-actions/entrypoint.sh
  flank-actions/slackService.kt
Labels: Tiger 🐯

#1167 fix: Flank action
  .github/workflows/release.yml
Labels: Snake 🐍

#1159 feat: Improve error message on matrix failures
  test_runner/src/main/kotlin/ftl/json/MatrixMap.kt
  test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
  test_runner/src/main/kotlin/ftl/reports/outcome/OutcomeMessageEnum.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/main/kotlin/ftl/run/exception/FlankException.kt
  test_runner/src/test/kotlin/ftl/json/MatrixMapTest.kt
  test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
Labels: Tiger 🐯

#1163 feat: Integration tests run when pr is approved and not draft
  .github/workflows/integration_tests.yml
  .github/workflows/macos_workflow.yml
  .github/workflows/ubuntu-workflow.yml
  .github/workflows/wsl-workflow.yml
Labels: Tiger 🐯

#1173 docs: Add FAQ section about sync problems
  README.md
Labels: Tiger 🐯
