Repository Flank/flank, pull requests merged in 2021-07, with the labels that each got.

#2059 ci: Slack notification follow up
  .github/workflows/create_new_release.yml
  .github/workflows/release_notes_generation.yml
Labels: Infrastructure, Snake 🐍

#2060 fix: Removed filtering default args when sending statistics to mixpanel
  test_runner/src/main/kotlin/ftl/analytics/PrepareConfiguration.kt
  test_runner/src/main/kotlin/ftl/analytics/StatisticDataFilters.kt
  test_runner/src/main/kotlin/ftl/analytics/UsageStatistics.kt
  test_runner/src/test/kotlin/ftl/analytics/UsageStatisticsTest.kt
Labels: Bug, P0, Tiger 🐯

#2055 feat: Expose test filters as standalone tool
  settings.gradle.kts
  tool/filter/README.md
  tool/filter/build.gradle.kts
  tool/filter/src/main/kotlin/flank/filter/Filter.kt
  tool/filter/src/main/kotlin/flank/filter/internal/FilterFromTestTarget.kt
  tool/filter/src/main/kotlin/flank/filter/internal/Test.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/AllOf.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/AnyOf.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/FromTestFile.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/Not.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/WithAnnotation.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/WithClassName.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/WithPackageName.kt
  tool/filter/src/main/kotlin/flank/filter/internal/factory/WithSize.kt
  tool/filter/src/test/kotlin/flank/filter/FilterKtTest.kt
  tool/filter/src/test/resources/dummy-tests-file.txt
  tool/filter/src/test/resources/exclude-tests.txt
Labels: Corellium, Feature, P0

#2046 feat: Parameterized tests options
  .gitignore
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidTestPlan.kt
  test_projects/android/apks/app-Extreme-Other-ParameterizedTests.apk
  test_projects/android/apks/app-Extreme-ParameterizedTests.apk
  test_projects/android/parameterizedTests/.gitignore
  test_projects/android/parameterizedTests/build.gradle
  test_projects/android/parameterizedTests/proguard-rules.pro
  test_projects/android/parameterizedTests/src/androidTest/java/com/flank/parameterizedtestsapplication/nonparameterized/SampleNonParameterizedTestPrimary.kt
  test_projects/android/parameterizedTests/src/androidTest/java/com/flank/parameterizedtestsapplication/nonparameterized/SampleNonParameterizedTestSecondary.kt
  test_projects/android/parameterizedTests/src/androidTest/java/com/flank/parameterizedtestsapplication/parameterized/SampleParameterizedTestExtreme.kt
  test_projects/android/parameterizedTests/src/androidTest/java/com/flank/parameterizedtestsapplication/parameterized/SampleParameterizedTestLarge.kt
  test_projects/android/parameterizedTests/src/androidTest/java/com/flank/parameterizedtestsapplication/parameterized/SampleParameterizedTestMedium.kt
  test_projects/android/parameterizedTests/src/androidTest/java/com/flank/parameterizedtestsapplication/parameterized/SampleParameterizedTestSmall.kt
  test_projects/android/parameterizedTests/src/main/AndroidManifest.xml
  test_projects/android/parameterizedTests/src/main/java/com/flank/parameterizedtestsapplication/FirstFragment.kt
  test_projects/android/parameterizedTests/src/main/java/com/flank/parameterizedtestsapplication/MainActivity.kt
  test_projects/android/parameterizedTests/src/main/java/com/flank/parameterizedtestsapplication/SecondFragment.kt
  test_projects/android/parameterizedTests/src/main/res/drawable-v24/ic_launcher_foreground.xml
  test_projects/android/parameterizedTests/src/main/res/drawable/ic_launcher_background.xml
  test_projects/android/parameterizedTests/src/main/res/layout/activity_main.xml
  test_projects/android/parameterizedTests/src/main/res/layout/content_main.xml
  test_projects/android/parameterizedTests/src/main/res/layout/fragment_first.xml
  test_projects/android/parameterizedTests/src/main/res/layout/fragment_second.xml
  test_projects/android/parameterizedTests/src/main/res/menu/menu_main.xml
  test_projects/android/parameterizedTests/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  test_projects/android/parameterizedTests/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  test_projects/android/parameterizedTests/src/main/res/mipmap-hdpi/ic_launcher.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-hdpi/ic_launcher_round.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-mdpi/ic_launcher.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-mdpi/ic_launcher_round.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-xhdpi/ic_launcher.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-xxhdpi/ic_launcher.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  test_projects/android/parameterizedTests/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  test_projects/android/parameterizedTests/src/main/res/navigation/nav_graph.xml
  test_projects/android/parameterizedTests/src/main/res/values-night/themes.xml
  test_projects/android/parameterizedTests/src/main/res/values/colors.xml
  test_projects/android/parameterizedTests/src/main/res/values/dimens.xml
  test_projects/android/parameterizedTests/src/main/res/values/strings.xml
  test_projects/android/parameterizedTests/src/main/res/values/themes.xml
  test_projects/android/parameterizedTests/src/test/java/com/flank/parameterizedtestsapplication/ExampleUnitTest.kt
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/AppTestPair.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidFlankConfig.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
Labels: Feature, New Option, P1, Tiger 🐯

#2058 feat: Install apks asynchronous
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InstallAndroidApps.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidApps.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
Labels: Corellium, Feature

#2066 fix: Parameterized Tests name change
  .github/workflows/full_suite_integration_tests.yml
  docs/index.md
  test_runner/flank.yml
Labels: Feature, P1, Snake 🐍, Tiger 🐯

#2057 refactor: Make the domain a source of defaults
  corellium/api/src/main/kotlin/flank/corellium/api/Authorization.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
Labels: Corellium, Refactor

#2056 feat: Test targets option for Corellium
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/domain/build.gradle.kts
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseTestCases.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
  docs/flank_corellium.md
  test_configs/flank-corellium.yml
  tool/apk/src/main/kotlin/flank/apk/Apk.kt
  tool/apk/src/main/kotlin/flank/apk/internal/Info.kt
  tool/apk/src/main/kotlin/flank/apk/internal/PackageName.kt
  tool/apk/src/main/kotlin/flank/apk/internal/TestCases.kt
  tool/apk/src/test/kotlin/flank/apk/ParseApkTest.kt
Labels: Corellium, Feature, P0

#2069 feat: Add option for running parallel tasks as synchronized sequence.
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Parallel.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Execution.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/Example.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/ExecuteKtTest.kt
Labels: Corellium, Feature

#2073 feat: Add Flank version info to requests
  test_runner/src/main/kotlin/ftl/client/google/run/Utils.kt
  test_runner/src/main/kotlin/ftl/client/google/run/android/GcAndroidTestMatrix.kt
  test_runner/src/main/kotlin/ftl/client/google/run/ios/GcIosTestMatrix.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: Feature, P2, Tiger 🐯

#2074 feat: Add Sentry to Flank Wrapper
  flank_wrapper/build.gradle.kts
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/CrashReporter.kt
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/RunFlankOnLatestVersion.kt
  flank_wrapper/src/main/resources/version.txt
Labels: Feature, Tiger 🐯

#2062 feat: Merge test method duration for parameterized classes
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/LoadPreviousDurations.kt
  tool/junit/src/main/kotlin/flank/junit/JUnit.kt
  tool/junit/src/main/kotlin/flank/junit/internal/CalculateMedianDurations.kt
  tool/junit/src/main/kotlin/flank/junit/internal/MergeDurations.kt
  tool/junit/src/main/kotlin/flank/junit/mapper/Structural.kt
  tool/junit/src/test/kotlin/flank/junit/internal/MergeDurationsKtTest.kt
  tool/junit/src/test/kotlin/flank/junit/mapper/StructuralKtTest.kt
Labels: Corellium, Feature, P0

#2079 refactor: Move Config.kt into :tool:config module.
  corellium/cli/build.gradle.kts
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  settings.gradle.kts
  tool/config/README.md
  tool/config/build.gradle.kts
  tool/config/src/main/kotlin/flank/config/Config.kt
Labels: Corellium

#2076 feat: Parameterized Tests - multiple
  docs/index.md
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Labels: Feature, New Option, P1, Tiger 🐯

#2081 refactor: Move legacy execution tool to standalone module.
  corellium/domain/build.gradle.kts
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  settings.gradle.kts
  tool/execution/linear/build.gradle.kts
  tool/execution/linear/src/main/kotlin/flank/exection/linear/Transform.kt
Labels: Corellium

#2080 feat: Improve :tool:execution:parallel.
  tool/execution/parallel/build.gradle.kts
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Create.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Execute.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Parallel.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Reduce.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Select.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Validate.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Verify.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/ContextProvider.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/DynamicType.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Execution.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Prepare.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Property.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Validate.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Verify.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/Example.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/ExecuteKtTest.kt
  tool/log/src/main/kotlin/flank/log/Event.kt
  tool/log/src/main/kotlin/flank/log/Logger.kt
Labels: Corellium

#2075 fix: Do not upload/read files when path starts with gs://
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadOtherFiles.kt
Labels: Bug, Tiger 🐯

#2085 feat: Add Analytics to Flank Wrapper
  buildSrc/src/main/kotlin/Modules.kt
  corellium/domain/build.gradle.kts
  flank-scripts/build.gradle.kts
  flank_wrapper/build.gradle.kts
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/CrashReporter.kt
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/DownloadLatestVersion.kt
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/FlankExecutor.kt
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/FlankWrapperAnalytics.kt
  flank_wrapper/src/main/resources/version.txt
  integration_tests/build.gradle.kts
  settings.gradle.kts
  test_runner/build.gradle.kts
  tool/analytics/README.md
  tool/analytics/mixpanel/build.gradle.kts
Labels: Feature, Tiger 🐯

#2072 feat: Integrate parallel execution in Corellium domain
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/run/test/android/Format.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/run/test/android/task/Apk.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/run/test/android/task/Args.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/run/test/android/task/Config.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/run/test/android/task/Corellium.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/run/test/android/task/JUnit.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/run/test/android/FormatKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/run/test/android/task/ArgsKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/run/test/android/task/ConfigKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/run/test/android/task/Util.kt
  corellium/domain/build.gradle.kts
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Authorize.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CleanUpInstances.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CreateOutputDir.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/DumpShards.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Finish.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/GenerateReport.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InstallApks.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InvokeDevices.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/LoadPreviousDurations.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseApkInfo.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseTestCases.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/PrepareShards.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumExample.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestParsingAndroid.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTestsKtTest.kt
  test_configs/flank-corellium.yml
  tool/execution/parallel/README.md
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Create.kt
Labels: Corellium

#2088 feat: Added firebase event to Mixpanel
  docs/flank_mixpanel_metrics.md
  test_runner/src/main/kotlin/ftl/analytics/InitUsageStatistics.kt
  test_runner/src/main/kotlin/ftl/analytics/SendAppId.kt
  test_runner/src/main/kotlin/ftl/analytics/SendConfiguration.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestAndroid.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestIos.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/XcTestData.kt
  test_runner/src/main/kotlin/ftl/reports/CostReport.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/test/kotlin/ftl/analytics/UsageStatisticsTest.kt
  test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/AnalyticsReport.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/SendConfiguration.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/Util.kt
Labels: P0, Tiger 🐯

#2095 fix: xArgs command update
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseSwiftTests.kt
Labels: Bug, Snake 🐍

#2098 feat: Improvements for :tool:execution:parallel
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Create.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Parallel.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Select.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/ContextProvider.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Execution.kt
  tool/log/src/main/kotlin/flank/log/Event.kt
Labels: Corellium, Feature

#2094 feat: Added Sdk Suppress Handling
  test_projects/android/app/src/androidTestMultiple/java/com.example.test_app/InstrumentedTestSdkSuppress.kt
  test_projects/android/app_sdksuppress/.gitignore
  test_projects/android/app_sdksuppress/build.gradle
  test_projects/android/app_sdksuppress/proguard-rules.pro
  test_projects/android/app_sdksuppress/src/main/AndroidManifest.xml
  test_projects/android/app_sdksuppress/src/main/java/com/example/test_app/MainActivity.kt
  test_projects/android/app_sdksuppress/src/main/res/drawable-v24/ic_launcher_foreground.xml
  test_projects/android/app_sdksuppress/src/main/res/drawable/ic_launcher_background.xml
  test_projects/android/app_sdksuppress/src/main/res/layout/activity_main.xml
  test_projects/android/app_sdksuppress/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  test_projects/android/app_sdksuppress/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  test_projects/android/app_sdksuppress/src/main/res/mipmap-hdpi/ic_launcher.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-hdpi/ic_launcher_round.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-mdpi/ic_launcher.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-mdpi/ic_launcher_round.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-xhdpi/ic_launcher.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-xxhdpi/ic_launcher.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  test_projects/android/app_sdksuppress/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  test_projects/android/app_sdksuppress/src/main/res/values/colors.xml
  test_projects/android/app_sdksuppress/src/main/res/values/strings.xml
  test_projects/android/app_sdksuppress/src/main/res/values/styles.xml
  test_projects/android/settings.gradle
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/SdkSupress.kt
  test_runner/src/main/kotlin/ftl/util/FlankTestMethod.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/SdkSuppressTest.kt
Labels: Android, BV, Bug, Tiger 🐯

#2097 fix: Incorrect calculations in JUnit tool
  tool/junit/src/main/kotlin/flank/junit/internal/MergeDurations.kt
  tool/junit/src/main/kotlin/flank/junit/internal/ParseJUnitTestResults.kt
  tool/junit/src/test/kotlin/flank/junit/internal/MergeDurationsKtTest.kt
Labels: Bug, Corellium, Feature

#2096 feat: Add num-flaky-test-attempts CLI option
  corellium/cli/src/main/kotlin/flank/corellium/cli/TestAndroidCommand.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/test/android/Format.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/test/android/task/Args.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/test/android/task/Config.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/FormatKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/task/ArgsKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/task/ConfigKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/task/Util.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/TestAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/ExecuteTests.kt
  test_configs/flank-corellium-many.yml
  test_configs/flank-corellium.yml
  test_configs/flank-ftl.yml
Labels: Corellium, Feature

#2101 chore: Add corrections to code documentation
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/Authorize.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/CreateOutputDir.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/DumpShards.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/ExecuteTests.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/Finish.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/GenerateReport.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/InstallApks.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/InvokeDevices.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/LoadPreviousDurations.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/ParseApkInfo.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/ParseTestCases.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/PrepareShards.kt
Labels: Corellium, Documentation

#2099 chore: Speeds up build disabling shardowJar plugin for :corellium:sandbox
  corellium/sandbox/build.gradle.kts
Labels: Corellium

#2102 docs: Generate tasks diagram
  corellium/domain/README.md
  corellium/domain/TestAndroid-execute.puml
  corellium/domain/build.gradle.kts
  corellium/domain/src/test/kotlin/flank/corellium/domain/AndroidTestDiagram.kt
  settings.gradle.kts
  tool/execution/parallel/plantuml/build.gradle.kts
  tool/execution/parallel/plantuml/src/main/kotlin/flank/exection/parallel/plantuml/PlantUml.kt
  tool/execution/parallel/plantuml/src/main/kotlin/flank/exection/parallel/plantuml/internal/GeneratePlantUmlFile.kt
  tool/execution/parallel/plantuml/src/main/kotlin/flank/exection/parallel/plantuml/internal/GeneratePlantUmlString.kt
Labels: Corellium, Documentation

#2106 refactor: Structural output login google
  test_runner/src/main/kotlin/ftl/adapter/GoogleUserAuthorizationRequest.kt
  test_runner/src/main/kotlin/ftl/api/UserAuthorization.kt
  test_runner/src/main/kotlin/ftl/client/google/UserAuth.kt
  test_runner/src/main/kotlin/ftl/domain/LoginGoogleAccount.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/auth/LoginCommand.kt
Labels: Feature, Tiger 🐯

#2092 feat: Rerun failed tests
  corellium/cli/src/main/kotlin/flank/corellium/cli/test/android/Format.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/FormatKtTest.kt
  corellium/domain/README.md
  corellium/domain/TestAndroid-execute.puml
  corellium/domain/TestAndroid_Device-execute.puml
  corellium/domain/src/main/kotlin/flank/corellium/domain/TestAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/device/task/ExecuteTestShard.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/device/task/InstallApks.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/device/task/ReleaseDevice.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/AvailableDevices.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/DispatchFailed.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/DispatchShards.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/DispatchTests.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/ExecuteTestQueue.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/GenerateReport.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/InitResultsChannel.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/InstallApks.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/InvokeDevices.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/AndroidTestDiagram.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/TestAndroidMockApiTest.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/TestAndroidParsingTest.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/test/android/task/ExecuteTestQueueKtTest.kt
  tool/execution/parallel/plantuml/src/main/kotlin/flank/exection/parallel/plantuml/internal/GeneratePlantUmlString.kt
Labels: Corellium, Feature

#2110 fix: Fix dry run
  test_runner/src/main/kotlin/ftl/mock/MockServer.kt
  test_runner/src/main/resources/android_catalog.json
  test_runner/src/main/resources/ios_catalog.json
  test_runner/src/test/kotlin/task/UpdateCatalogFixtures.kt
Labels: Bug, P2, Tiger 🐯

#2108 feat: Added Gradle Plugin to check if helpers modules version get updated
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Utils.kt
  check_version_updated/build.gradle.kts
  check_version_updated/settings.gradle.kts
  check_version_updated/src/main/kotlin/com/github/flank/gradle/CheckVersionUpdated.kt
  check_version_updated/src/main/kotlin/com/github/flank/gradle/CheckVersionUpdatedTask.kt
  flank-scripts/build.gradle.kts
  flank_wrapper/build.gradle.kts
  flank_wrapper/src/main/resources/version.txt
  settings.gradle.kts
Labels: Feature, Tiger 🐯
