Repository Flank/flank, pull requests merged in 2021-01, with the labels that each got.

#1443 ci: Add missing step
  .github/workflows/update_dependencies_and_client.yml
Labels: Snake 🐍

#1447 ci: Fix dependency update workflow
  .github/workflows/update_dependencies_and_client.yml
Labels: Snake 🐍

#1453 fix: Fix problem with test-runner-class
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Labels: Bug

#1451 ci: Added CLA assistant
  .github/workflows/cla.yml
  contributing.md
Labels: Dragon 🐲

#1428 feat: Rewrite pre-commit hook & ktlint apply to idea into Flank Scripts
  .githooks/linkHooks.bat
  .githooks/linkHooks.sh
  .gitignore
  buildSrc/src/main/kotlin/Versions.kt
  common/src/main/kotlin/flank.common/Files.kt
  docs/onboarding/1_environment_setup.md
  docs/onboarding/2_contribution.md
  flank-scripts/README.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/Main.kt
  flank-scripts/src/main/kotlin/flank/scripts/contribution/ContributionCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/contribution/githooks/GitHooksLinkCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/contribution/ideaktlint/IdeaKtlintCodeStyleCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/GitHubIssuePropertiesCopy.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/ShellExecute.kt
  flank-scripts/src/test/kotlin/flank/common/FilesTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/integration/ProcessResultTest.kt
Labels: Feature, Styling, Tiger 🐯

#1465 fix: CI failures on performance tests
  .github/workflows/ubuntu-workflow.yml
Labels: Bug

#1466 refactor: Change packages in the common module
  common/src/main/kotlin/flank/common/Archive.kt
  common/src/main/kotlin/flank/common/Files.kt
  common/src/main/kotlin/flank/common/Net.kt
  common/src/main/kotlin/flank/common/Os.kt
  common/src/main/kotlin/flank/common/OutputLogger.kt
  common/src/main/kotlin/flank/common/Strings.kt
  common/src/main/kotlin/flank/common/Zip.kt
Labels: Snake 🐍, Tech Debt

#1456 ci: Update config for CLA
  .github/workflows/cla.yml
Labels: Feature

#1468 ci: Use pointer workflows to preserve run date
  .github/workflows/full_suite_integration_tests.yml
  .github/workflows/integration_tests_pointer.yml
  .github/workflows/update_dependencies_and_client.yml
  .github/workflows/update_dependencies_pointer.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/integration/WorkflowSummary.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/LastSDKUpdateRun.kt
Labels: Dragon 🐲

#1473 refactor: Update picocli to latest version
  buildSrc/src/main/kotlin/Versions.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/CommonRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/config/Create.kt
Labels: Feature, Tiger 🐯

#1450 refactor: Enable properties file in flank scripts
  build.gradle.kts
  common/.gitignore
  common/build.gradle.kts
  common/src/main/kotlin/flank/common/Environment.kt
  common/src/main/kotlin/flank/common/PathHelper.kt
  common/src/main/kotlin/flank/common/config/FlankProperties.kt
  flank-scripts/README.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/contribution/ideaktlint/IdeaKtlintCodeStyleCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/GithubApi.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubSetAssigneesRequest.kt
  flank-scripts/src/main/kotlin/flank/scripts/github/objects/GitHubSetLabelsRequest.kt
  flank-scripts/src/main/kotlin/flank/scripts/integration/IssueList.kt
  flank-scripts/src/main/kotlin/flank/scripts/integration/PrepareMessage.kt
  flank-scripts/src/main/kotlin/flank/scripts/integration/WorkflowSummary.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/SetAssignees.kt
  flank-scripts/src/main/kotlin/flank/scripts/pullrequest/SetLabels.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnag.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/BuildFlank.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/apiclient/UpdateApiJsonCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/CheckForSDKUpdateCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/CommitList.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/Extensions.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/LastSDKUpdateRun.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/firebase/sdk/OpenedUpdates.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ios/BuildExample.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ios/RunFtlLocal.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ios/SetupIosEnvCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ios/UniversalFramework.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildAndroid.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildEarlGreyExampleCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildFlankExampleCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildGameLoopExampleCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildIosIPA.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildIosTestArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/BuildTestPlansExample.kt
  flank-scripts/src/main/kotlin/flank/scripts/shell/ops/GoOpsCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/Constants.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/TestArtifactsRepo.kt
  flank-scripts/src/main/kotlin/flank/scripts/zenhub/ZenHubAPI.kt
Labels: Tiger 🐯

#1471 feat: Migrate from bugsnag to sentry
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
  integration_tests/src/test/resources/compare/GameloopIT-ios-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/Main.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/config/FtlConstants.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
  test_runner/src/main/kotlin/ftl/log/LogbackLogger.kt
  test_runner/src/main/kotlin/ftl/log/Loggers.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/common/SaveSessionId.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/main/kotlin/ftl/util/BugsnagInitHelper.kt
  test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/util/FlankSentryInitHelperTest.kt
  test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Labels: Feature

#1490 fix: Fix incorrect method usage on master
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/github/commons/LastWorkflowRunDate.kt
  test_runner/src/main/kotlin/ftl/run/common/SaveSessionId.kt
Labels: Snake 🐍

#1470 fix: Resolve Fails on Windows
  .github/workflows/full_suite_integration_tests.yml
  .github/workflows/update_dependencies_and_client.yml
  common/src/main/kotlin/flank/common/Files.kt
  common/src/test/kotlin/flank/common/FilesTest.kt
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/github/commons/LastWorkflowRunDate.kt
  flank-scripts/src/main/kotlin/flank/scripts/testartifacts/core/LinkArtifacts.kt
  flank-scripts/src/test/kotlin/flank/scripts/shell/firebase/sdk/SDKUpdateTest.kt
Labels: Bug, Tiger 🐯

#1474 feat: Amend pre-commit hook
  .githooks/pre-commit
Labels: Feature, Styling, Tiger 🐯

#1495 docs: Choose analytics tool
  docs/analytics_comparsion.md
Labels: Feature

#1506 fix: Improve Sentry logging for tests
  .github/workflows/release.yml
  build.gradle.kts
  common/src/main/kotlin/flank/common/config/FlankProperties.kt
  common/src/test/kotlin/flank/common/config/FlankPropertiesTest.kt
  docs/error_monitoring.md
  docs/flank_secrets.md
  docs/index.md
  docs/readme.md
  docs/release_process.md
  flank-scripts/README.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/exceptions/FlankScriptsExceptionMappers.kt
  flank-scripts/src/main/kotlin/flank/scripts/exceptions/FlankScriptsExceptions.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/ReleaseCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/BugSnagRequest.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/BugSnagResponse.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnag.kt
  flank-scripts/src/main/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnagCommand.kt
  flank-scripts/src/test/kotlin/flank/scripts/FuelMockServer.kt
  flank-scripts/src/test/kotlin/flank/scripts/exceptions/FlankScriptsExceptionMappersTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/exceptions/FlankScriptsExceptionsTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnagCommandTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/release/updatebugsnag/UpdateBugSnagTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/SerializationTest.kt
  test_runner/proguard/config.pro
  test_runner/src/main/kotlin/ftl/Main.kt
  test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/MainTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-success.yml
  test_runner/src/test/kotlin/ftl/util/FlankSentryInitHelperTest.kt
  test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Labels: Bug, Tech Debt, Tiger 🐯

#1504 feat: Sending configuration to mixpanel
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  docs/index.md
  integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
  integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
  integration_tests/src/test/resources/compare/GameloopIT-ios-compare
  integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
  test_runner/build.gradle.kts
  test_runner/flank.ios.yml
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/analytics/PrepareConfiguration.kt
  test_runner/src/main/kotlin/ftl/analytics/SendUsageStatistics.kt
  test_runner/src/main/kotlin/ftl/analytics/StatisticDataFilters.kt
  test_runner/src/main/kotlin/ftl/analytics/UsageStatistics.kt
  test_runner/src/main/kotlin/ftl/analytics/UsageStatisticsClient.kt
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
  test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
  test_runner/src/test/kotlin/ftl/analytics/UsageStatisticsTest.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: Feature

#1515 style: Add Kotlin Lint to tests
  build.gradle.kts
Labels: Snake 🐍

#1521 fix: Fix NPE and logging
  common/src/main/kotlin/flank/common/PathHelper.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
Labels: Bug

#1514 test: Update compare file and make url option not required
  .github/workflows/full_suite_integration_tests.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/integration/ProcessResultCommand.kt
  flank-scripts/src/test/kotlin/flank/scripts/integration/ProcessResultTest.kt
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
Labels: Bug, Tiger 🐯

#1525 test: Add missing iOS options in IT
  integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
  integration_tests/src/test/resources/compare/GameloopIT-ios-compare
Labels: Snake 🐍

#1526 fix: Windows Integration tests
  integration_tests/src/test/kotlin/integration/GameloopIT.kt
Labels: Bug, Tiger 🐯

#1535 ci: Windows integration test
  .github/workflows/full_suite_integration_tests.yml
Labels: Feature, Tiger 🐯

#1534 ci: Added Windows workflow
  .github/workflows/windows_workflow.yml
  common/src/main/kotlin/flank/common/Files.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
  test_runner/src/test/kotlin/ftl/analytics/UsageStatisticsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/common/InstallParseBinariesTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/common/ParseObjTestsKtTest.kt
  test_runner/src/test/kotlin/ftl/ios/xctest/common/ParseSwiftTestsKtTest.kt
Labels: Feature, Tiger 🐯

#1537 ci: Integration Test for all OS's
  .github/workflows/full_suite_integration_tests.yml
Labels: Bug, Feature, Snake 🐍, Tiger 🐯

#1546 fix: Fix flaky FilesTest
  buildSrc/src/main/kotlin/Versions.kt
  flank-scripts/build.gradle.kts
  flank-scripts/src/test/kotlin/flank/common/FilesTest.kt
Labels: Snake 🐍

#1540 fix: dummy var for pr
  .github/workflows/full_suite_integration_tests.yml
Labels: Bug
