Repository Flank/flank, pull requests merged in 2021-08, with the labels that each got.

#2113 feat: Get apk details with retry
  test_runner/src/main/kotlin/ftl/client/google/AppDetails.kt
  test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
Labels: Feature

#2118 feat: Added project ID to sentry
  test_runner/src/main/kotlin/ftl/domain/RunTestAndroid.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestIos.kt
  test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
Labels: Feature

#2119 ci: Simple GHA Dogfood script
  .github/workflows/action_it_tests.yml
Labels: Feature, P2, Tiger 🐯

#2107 refactor: Mixpanel module API & implementation
  flank_wrapper/build.gradle.kts
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/CrashReporter.kt
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/FlankWrapperAnalytics.kt
  flank_wrapper/src/main/resources/version.txt
  test_runner/src/main/kotlin/ftl/analytics/InitUsageStatistics.kt
  test_runner/src/main/kotlin/ftl/analytics/SendConfiguration.kt
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/XcTestData.kt
  test_runner/src/main/kotlin/ftl/mock/MockServer.kt
  test_runner/src/main/kotlin/ftl/reports/CostReport.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/common/SaveSessionId.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/ftl/analytics/UsageStatisticsTest.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/AnalyticsReport.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/Mixpanel.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/SendConfiguration.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/StatisticDataFilters.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/UsageStatisticsClient.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/Util.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Add.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Configure.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Filter.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Mapper.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Report.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Send.kt
Labels: Refactor

#2122 fix: Envs from additional apks not override default values
  test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
Labels: Bug

#2127 refactor: Bash command execution
  test_runner/src/main/kotlin/ftl/adapter/CommandRunner.kt
  test_runner/src/main/kotlin/ftl/api/Bash.kt
  test_runner/src/main/kotlin/ftl/client/RunShellCommand.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseObjTests.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseSwiftTests.kt
  test_runner/src/main/kotlin/ftl/mock/MockServer.kt
  test_runner/src/main/kotlin/ftl/util/Bash.kt
  test_runner/src/test/kotlin/ftl/util/BashTest.kt
Labels: Feature, Tiger 🐯

#2128 build: Fix build warnings
  corellium/adapter/build.gradle.kts
  corellium/domain/build.gradle.kts
  integration_tests/build.gradle.kts
  tool/analytics/build.gradle.kts
  tool/analytics/mixpanel/build.gradle.kts
  tool/config/build.gradle.kts
  tool/execution/parallel/build.gradle.kts
Labels: Tech Debt, Corellium

#2131 feat: Implement env parsing
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/flank.local.yml
Labels: Feature

#2140 fix: Disable mixpanel in tests
  .github/workflows/macos_workflow.yml
  flank_wrapper/build.gradle.kts
  flank_wrapper/src/main/kotlin/com/github/flank/wrapper/internal/FlankWrapperAnalytics.kt
  flank_wrapper/src/main/resources/version.txt
  integration_tests/src/test/resources/cases/flank_ios_gameloop_success.yml
  test_runner/src/main/kotlin/ftl/analytics/InitUsageStatistics.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/Mixpanel.kt
Labels: Bug

#2142 fix: Add retry and silent crash to mixpanel send method
  flank_wrapper/.gitignore
  flank_wrapper/build.gradle.kts
  tool/analytics/mixpanel/build.gradle.kts
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Send.kt
  tool/analytics/mixpanel/src/main/kotlin/flank/tool/analytics/mixpanel/internal/Utils.kt
  tool/analytics/mixpanel/src/test/kotlin/flank/tool/analytics/mixpanel/internal/UtilsTest.kt
Labels: Bug

#2139 refactor: Structural output refresh last run
  buildSrc/src/main/kotlin/Dependencies.kt
  check_version_updated/src/main/kotlin/com/github/flank/gradle/CheckVersionUpdatedTask.kt
  flank_wrapper/.gitignore
  flank_wrapper/build.gradle.kts
  flank_wrapper/src/main/resources/version.txt
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt
  test_runner/src/main/kotlin/ftl/domain/RefreshLastRun.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestAndroid.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestIos.kt
  test_runner/src/main/kotlin/ftl/presentation/RunState.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/FirebaseCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/MainCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/refresh/HandleRefreshRunState.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/refresh/RefreshCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/reportmanager/HandleReportManagerState.kt
  test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
  test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
  test_runner/src/main/kotlin/ftl/run/common/GetLastMatrices.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/RefreshCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/presentation/RunStateTest.kt
  test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
Labels: Refactor, Corellium

#2121 feat: Calculate flaky tests from reruns
  corellium/cli/src/main/kotlin/flank/corellium/cli/TestAndroidCommand.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/test/android/task/Args.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/test/android/task/Config.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/task/ArgsKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/task/ConfigKtTest.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/test/android/task/Util.kt
  corellium/domain/README.md
  corellium/domain/TestAndroid-execute.puml
  corellium/domain/src/main/kotlin/flank/corellium/domain/TestAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/DispatchFailed.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/GenerateReport.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/test/android/task/ProcessResults.kt
  docs/flank_corellium.md
  test_configs/flank-corellium-many.yml
  test_configs/flank-corellium.yml
  tool/config/src/main/kotlin/flank/config/Config.kt
  tool/instrument/log/src/main/kotlin/flank/instrument/log/Parser.kt
  tool/junit/src/main/kotlin/flank/junit/JUnit.kt
  tool/junit/src/main/kotlin/flank/junit/mapper/Structural.kt
Labels: Feature, Corellium

#2158 feat: Adapt new iOS xml structure
  test_runner/src/main/kotlin/ftl/client/junit/JUnitXmlParser.kt
Labels: Bug, P0
