Repository Flank/flank, pull requests merged in 2021-02, with the labels that each got.

#1557 fix: Move shards json to result directory
  integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
  integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/run/DumpShards.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
Labels: Bug, Tiger 🐯

#1560 fix: Fix IT workflow for windows
  .github/workflows/full_suite_integration_tests.yml
Labels: Tiger 🐯

#1564 fix: windows issues
  .github/workflows/full_suite_integration_tests.yml
  common/src/main/kotlin/flank/common/Files.kt
  common/src/test/kotlin/flank/common/FilesTest.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
Labels: Bug

#1559 feat: Add storing output as json
  docs/index.md
  integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
  integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
  integration_tests/src/test/resources/compare/GameloopIT-ios-compare
  integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
  test_runner/flank.ios.yml
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
  test_runner/src/main/kotlin/ftl/reports/CostReport.kt
  test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
  test_runner/src/main/kotlin/ftl/reports/outcome/TestOutcome.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReport.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReportConfiguration.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReportLoggers.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReportType.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/main/kotlin/ftl/util/Billing.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/reports/output/OutputReportLoggersTest.kt
  test_runner/src/test/kotlin/ftl/reports/output/OutputReportTest.kt
Labels: Feature, Tiger 🐯

#1566 docs: Flank-scripts command overview
  docs/flank-scripts/command_overview.md
Labels: Refactor

#1572 refactor: Flank scripts features not depends on each other
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/shell/BuildFtlCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/cli/shell/RunFtlLocalCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/cli/shell/UniversalFrameworkCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/cli/shell/buildexample/BuildExampleCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/ci/AppendReleaseNotes.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/ci/CreateReleaseNotes.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/common/ConventionalCommitFormatter.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/common/EarlGreyExampleConsts.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/common/GenerateChangeLog.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/common/ReleaseNotesWithType.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/release/hub/ReleaseFlank.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/SetupIosEnv.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildEarlGreyExample.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildExample.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildFtl.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildIosIPA.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/BuildIosTestArtifacts.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/IosBuildCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/LipoHelper.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/RunFtlLocal.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/shell/buildexample/ios/UniversalFramework.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/ci/releasenotes/AppendReleaseNotesTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/ci/releasenotes/ConventionalCommitFormatterTest.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/ci/releasenotes/ReleaseNotesWithTypeTest.kt
Labels: Refactor, Tiger 🐯

#1583 docs: flank-scripts ops package organization
  docs/flank-scripts/ops_structure.md
Labels: Refactor, Tiger 🐯

#1581 fix: Fixes for Workflow files & IT tests
  .github/workflows/full_suite_integration_tests.yml
  integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
  integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
Labels: Tiger 🐯

#1590 docs: Github action SDD proposal
  docs/flank-github-action/flank_github_acton_sdd.md
Labels: Feature, Research, Tiger 🐯

#1585 fix: Print Flank version only on run command
  test_runner/src/main/kotlin/ftl/Main.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosRunCommand.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
Labels: Bug, P1, Tiger 🐯

#1593 fix: Remove GameloopIT test for IOS
  common/src/main/kotlin/flank/common/Os.kt
  integration_tests/src/test/kotlin/integration/GameloopIT.kt
Labels: Bug, IT_Failed

#1614 ci: publish flank to maven central
  .github/workflows/release.yml
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  docs/index.md
  docs/release_process.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/release/DeleteSnapshotCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/cli/release/ReleaseCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/cli/release/SyncWithMavenCentralCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/jfrog/DeleteOldSnapshot.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/jfrog/JFrogCommandHelper.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/jfrog/SyncMaven.kt
  flank-scripts/src/test/kotlin/flank/scripts/cli/release/SyncWithMavenCentralCommandTest.kt
  test_runner/build.gradle.kts
Labels: Feature, Infrastructure, Tiger 🐯

#1617 fix: release job
  .github/workflows/release.yml
Labels: Snake 🐍

#1618 ci: Publish Flank-scripts to Github
  .github/workflows/release_flank_scripts.yml
  build.gradle.kts
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  flank-scripts/build.gradle.kts
Labels: Feature, Tiger 🐯

#1619 fix: Releasing flank-scripts
  .github/workflows/release_flank_scripts.yml
  flank-scripts/build.gradle.kts
Labels: Bug

#1620 fix: Authenticate in Github CLI before release Flank-Scripts
  .github/workflows/create_new_release.yml
  .github/workflows/full_suite_integration_tests.yml
  .github/workflows/pr_checks.yml
  .github/workflows/release.yml
  .github/workflows/release_flank_scripts.yml
  .github/workflows/release_notes_generation.yml
  .github/workflows/update_dependencies_and_client.yml
  flank-scripts/build.gradle.kts
Labels: Bug

#1624 feat: Part 1 of multiple OS IT tests
  .github/workflows/full_suite_integration_tests.yml
Labels: Feature, Tiger 🐯

#1626 fix: Spacing fix for yml file
  .github/workflows/full_suite_integration_tests.yml
Labels: Snake 🐍

#1628 fix: Remove analytics from integration tests
  integration_tests/src/test/resources/cases/all_test_filtered_android.yml
  integration_tests/src/test/resources/cases/all_test_filtered_ios.yml
  integration_tests/src/test/resources/cases/dump_shards_android.yml
  integration_tests/src/test/resources/cases/dump_shards_ios.yml
  integration_tests/src/test/resources/cases/flank_android_gameloop_success.yml
  integration_tests/src/test/resources/cases/flank_android_ignore_failed.yml
  integration_tests/src/test/resources/cases/flank_android_multiple_apk.yml
  integration_tests/src/test/resources/cases/flank_android_multiple_devices.yml
  integration_tests/src/test/resources/cases/flank_android_run_timeout.yml
  integration_tests/src/test/resources/cases/flank_ios_gameloop_success.yml
  integration_tests/src/test/resources/cases/sanity_robo.yml
  integration_tests/src/test/resources/cases/test_filtering_android.yml
Labels: Feature, Snake 🐍, Tiger 🐯

#1631 fix: Update compare files in IT
  .github/workflows/full_suite_integration_tests.yml
  integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
  integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
  integration_tests/src/test/resources/compare/GameloopIT-ios-compare
  integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
Labels: Bug, Snake 🐍

#1635 feat: Part 2 of IT tests
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/integrationtests/ProcessResultCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/ProcessIntegrationTestsResult.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/ITResult.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/PrepareMessage.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/integrationtests/DummyITRunState.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/integrationtests/ProcessResultTest.kt
Labels: Tiger 🐯

#1627 docs: Explore test-targets-for-shards SDD
  docs/feature/1532-explore-test-target-for-shards-with-extra-features.md
Labels: Documentation, Feature, Research, Tiger 🐯
