Repository Flank/flank, pull requests merged in 2021-03, with the labels that each got.

#1640 ci: Fix gradle command
  .github/workflows/release.yml
Labels: Snake 🐍

#1642 ci: Fix release workflow
  .github/workflows/release.yml
Labels: Snake 🐍

#1641 ci: Add missing subcommands
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/release/ReleaseCommand.kt
Labels: Snake 🐍

#1639 ci: Update workflow file
  .github/workflows/full_suite_integration_tests.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/ProcessIntegrationTestsResult.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/ITResult.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/PrepareMessage.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/integrationtests/ProcessResultTest.kt
Labels: Snake 🐍

#1649 fix: JUnitReport.xml only contained 50 test results
  test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
  test_runner/src/main/kotlin/ftl/reports/api/CreateTestExecutionData.kt
  test_runner/src/test/kotlin/ftl/reports/api/CreateTestExecutionDataKtTest.kt
Labels: Bug, P0, Tiger 🐯

#1653 ci: Parse env object to JSON
  .github/workflows/full_suite_integration_tests.yml
Labels: Snake 🐍, Tech Debt

#1654 ci: Treat env json as a string
  .github/workflows/full_suite_integration_tests.yml
Labels: Snake 🐍

#1655 feat: Update Flank Slack release notifier
  .github/workflows/release.yml
Labels: Feature, Snake 🐍

#1651 refactor: Change packages of commands
  test_runner/src/main/kotlin/ftl/cli/firebase/test/AndroidCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/IosCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidLocalesCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidModelsCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidOrientationsCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidVersionsCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosLocalesCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosModelsCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosOrientationsCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/ios/IosVersionsCommand.kt
Labels: Feature, Snake 🐍

#1659 feat: Remove flank-actions
  action.yml
  flank-actions/Dockerfile
  flank-actions/common.kt
  flank-actions/compile.sh
  flank-actions/entrypoint.sh
  flank-actions/sendMessage
  flank-actions/sendMessage.kts
  flank-actions/slackService.kt
Labels: Feature, Tiger 🐯

#1662 fix: Fix NPE in GcToolResults
  test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
Labels: Bug, P0, Snake 🐍, Tiger 🐯

#1661 test: Implement logic to clear LocalGcs after each test
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
  test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
  test_runner/src/test/kotlin/ftl/test/util/FlankTestRunner.kt
  test_runner/src/test/kotlin/ftl/test/util/LocalGcs.kt
Labels: Tech Debt, Tiger 🐯

#1644 docs: Add Flank output research docs
  docs/flank-output-investigation/flank_current_output.md
  docs/flank-output-investigation/flank_output_propositon.md
  docs/flank-output-investigation/gcloud_current_output.md
Labels: Feature, Research, Tiger 🐯

#1660 feat: Add Flank GitHub action
  action.yml
  docs/flank-scripts/README.md
  docs/flank-scripts/command_overview.md
  docs/flank-scripts/ops_structure.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/github/DownloadFlankCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/cli/github/GitHubCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/data/github/GithubApi.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/github/DownloadFlank.kt
  flank-scripts/src/test/kotlin/flank/scripts/GithubMockServerHandler.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/github/DownloadFlankTest.kt
Labels: Feature, Tiger 🐯

#1663 feat: Added reading service account in Github action
  action.yml
  common/src/main/kotlin/flank/common/Files.kt
  docs/flank-scripts/command_overview.md
  docs/flank-scripts/ops_structure.md
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/firebase/FirebaseCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/cli/firebase/SaveServiceAccountCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/firebase/SaveServiceAccount.kt
  flank-scripts/src/test/kotlin/flank/scripts/FuelMockServer.kt
  flank-scripts/src/test/kotlin/flank/scripts/ops/firebase/SaveServiceAccountTest.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/config/Credentials.kt
  test_runner/src/test/kotlin/ftl/args/FetchProjectIdTest.kt
Labels: Feature, Tiger 🐯

#1673 feat: Run Flank Github action with config provided by user
  action.yml
Labels: Feature, Tiger 🐯

#1679 ci: Fix publishing snapshots
  .github/workflows/release.yml
Labels: Bug, Snake 🐍

#1675 feat: Return directories path in Flank Github action
  action.yml
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
Labels: Feature, Tiger 🐯

#1680 fix: Fix output report error with dump shards
  common/src/main/kotlin/flank/common/Files.kt
  common/src/test/kotlin/flank/common/FilesTest.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReport.kt
  test_runner/src/test/kotlin/ftl/reports/output/OutputReportTest.kt
Labels: Bug, Snake 🐍

#1693 fix: white space in Github action
  action.yml
Labels: Bug, Snake 🐍

#1694 fix: Output path to local results github action
  action.yml
Labels: Bug, Snake 🐍

#1701 docs: Create Github marketplace documentation for Flank action
  README.md
  docs/flank-github-action/store_documentation.md
Labels: Feature, Tiger 🐯

#1709 docs: Desktop POC SDD
  docs/desktop/flank_desktop.md
  docs/desktop/flank_mock.png
Labels: Feature, Tiger 🐯

#1704 feat: Add app name to the test result
  integration_tests/src/test/kotlin/integration/IntergrationTestsUtils.kt
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
  test_runner/src/main/kotlin/ftl/json/SavedMatrixTableUtil.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReportLoggers.kt
  test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt
  test_runner/src/test/kotlin/ftl/reports/output/OutputReportLoggersTest.kt
Labels: Feature, Tiger 🐯

#1715 feat: Add option to skip config validation
  integration_tests/src/test/resources/compare/AllTestFilteredIT-android-compare
  integration_tests/src/test/resources/compare/AllTestFilteredIT-ios-compare
  integration_tests/src/test/resources/compare/GameloopIT-android-compare
  integration_tests/src/test/resources/compare/GameloopIT-ios-compare
  integration_tests/src/test/resources/compare/IgnoreFailedIT-compare
  integration_tests/src/test/resources/compare/MultipleApksIT-compare
  integration_tests/src/test/resources/compare/MultipleDevicesIT-android-compare
  integration_tests/src/test/resources/compare/RunTimeoutIT-compare
  integration_tests/src/test/resources/compare/SanityRoboIT-compare
  integration_tests/src/test/resources/compare/TestFilteringIT-compare
  test_runner/flank.ios.yml
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/IArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
Labels: Feature, New Option, P0, Tiger 🐯

#1707 docs: Add cli class diagram
  docs/hld/presentation/cli/cli-class-diagram.puml
  docs/hld/presentation/cli/readme.md
Labels: Documentation, Tech Debt

#1724 refactor: Separate main function from MainCommand
  test_runner/src/main/kotlin/ftl/Main.kt
  test_runner/src/main/kotlin/ftl/cli/MainCommand.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/MainTest.kt
  test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
Labels: Refactor, Snake 🐍

#1719 test: Improve integration tests
  common/src/main/kotlin/flank/common/OutputReportCostNode.kt
  common/src/main/kotlin/flank/common/OutputReportKeys.kt
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
  integration_tests/src/test/kotlin/integration/GameloopIT.kt
  integration_tests/src/test/kotlin/integration/IgnoreFailedIT.kt
  integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
  integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt
  integration_tests/src/test/kotlin/integration/RunTimeoutIT.kt
  integration_tests/src/test/kotlin/integration/SanityRoboIT.kt
  integration_tests/src/test/kotlin/integration/TestFilteringIT.kt
  integration_tests/src/test/kotlin/utils/IntergrationTestsUtils.kt
  integration_tests/src/test/kotlin/utils/LoadJsonResults.kt
  integration_tests/src/test/kotlin/utils/OutputHelper.kt
  integration_tests/src/test/kotlin/utils/OutputReportParser.kt
  integration_tests/src/test/resources/cases/all_test_filtered_android.yml
  integration_tests/src/test/resources/cases/all_test_filtered_ios.yml
  integration_tests/src/test/resources/cases/dump_shards_android.yml
  integration_tests/src/test/resources/cases/dump_shards_ios.yml
  integration_tests/src/test/resources/cases/flank_android_gameloop_success.yml
  integration_tests/src/test/resources/cases/flank_android_ignore_failed.yml
  integration_tests/src/test/resources/cases/flank_android_multiple_apk.yml
  integration_tests/src/test/resources/cases/flank_android_multiple_devices.yml
  integration_tests/src/test/resources/cases/flank_android_run_timeout.yml
  integration_tests/src/test/resources/cases/sanity_robo.yml
  integration_tests/src/test/resources/cases/test_filtering_android.yml
  test_runner/src/main/kotlin/ftl/reports/output/OutputReport.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReportLoggers.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/simple-android-flank.yml
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-single-success.yml
  test_runner/src/test/kotlin/ftl/reports/output/OutputReportTest.kt
Labels: Feature, Tiger 🐯

#1732 fix: Follow up refactor fix
  test_runner/build.gradle.kts
Labels: Bug, IT_Failed, Snake 🐍

#1730 test: Added app with many tests
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ops/assemble/android/BuildManyTestsApk.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/assemble/android/RunAndroidOps.kt
  test_projects/android/app_many_tests/.gitignore
  test_projects/android/app_many_tests/build.gradle
  test_projects/android/app_many_tests/proguard-rules.pro
  test_projects/android/app_many_tests/src/androidTest/java/com/example/app/many/tests/ManyParametrizedTests.kt
  test_projects/android/app_many_tests/src/androidTest/java/com/example/app/many/tests/ManyTests.kt
  test_projects/android/app_many_tests/src/main/AndroidManifest.xml
  test_projects/android/app_many_tests/src/main/java/com/example/app/many/tests/MainActivity.kt
  test_projects/android/app_many_tests/src/main/res/drawable-v24/ic_launcher_foreground.xml
  test_projects/android/app_many_tests/src/main/res/drawable/ic_launcher_background.xml
  test_projects/android/app_many_tests/src/main/res/layout/activity_main.xml
  test_projects/android/app_many_tests/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  test_projects/android/app_many_tests/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  test_projects/android/app_many_tests/src/main/res/mipmap-hdpi/ic_launcher.png
  test_projects/android/app_many_tests/src/main/res/mipmap-hdpi/ic_launcher_round.png
  test_projects/android/app_many_tests/src/main/res/mipmap-mdpi/ic_launcher.png
  test_projects/android/app_many_tests/src/main/res/mipmap-mdpi/ic_launcher_round.png
  test_projects/android/app_many_tests/src/main/res/mipmap-xhdpi/ic_launcher.png
  test_projects/android/app_many_tests/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  test_projects/android/app_many_tests/src/main/res/mipmap-xxhdpi/ic_launcher.png
  test_projects/android/app_many_tests/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  test_projects/android/app_many_tests/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  test_projects/android/app_many_tests/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  test_projects/android/app_many_tests/src/main/res/values/colors.xml
  test_projects/android/app_many_tests/src/main/res/values/strings.xml
  test_projects/android/app_many_tests/src/main/res/values/styles.xml
  test_projects/android/ops.sh
  test_projects/android/settings.gradle
Labels: Tiger 🐯

#1733 docs: Add flank component diagram
  docs/hld/flank-component-diagram.puml
Labels: Documentation, Tech Debt

#1717 feat: Windows Updates For Integration Tests
  common/src/main/kotlin/flank/common/Files.kt
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ops/updatebinaries/UpdateAtomic.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/updatebinaries/UpdateLlvm.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/updatebinaries/UpdateSwift.kt
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
  test_runner/bash/flank.bat
  test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseObjTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
Labels: Feature, Tiger 🐯

#1737 test: Add IT for large shard test suite
  integration_tests/src/test/kotlin/integration/ManyTestsOnSingleShardIT.kt
  integration_tests/src/test/resources/cases/flank_android_many_tests_on_single_shard.yml
Labels: Tech Debt, Tiger 🐯

#1588 refactor: Investigate and create proposal
  docs/gcloud/google_api_usecases.md
  docs/refactor/diagram.md
  docs/refactor/flank_run/flank_run.md
  docs/refactor/flank_run/flank_run_refactor_sdd.md
  docs/refactor/important_cli_commands.md
  docs/refactor/investigation.md
  docs/refactor/proposal.md
  docs/refactor/steps.md
  docs/refactor/uml/android_gameloop_context_to_config.puml
  docs/refactor/uml/android_instrumentation_context_to_config.puml
  docs/refactor/uml/android_robo_context_to_config.puml
  docs/refactor/uml/flank_activity_diagram.puml
  docs/refactor/uml/flank_activity_proposal.puml
  docs/refactor/uml/flank_android_sharding_diagram.puml
  docs/refactor/uml/flank_config_args_class.puml
  docs/refactor/uml/flank_ios_sharding_diagram.puml
  docs/refactor/uml/flank_run_relations.puml
Labels: Research, Tiger 🐯

#1741 refactor: Rename cli package
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidLocalesCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesDescribeCommand.kt
  test_runner/src/main/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesDescribeCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesListCommandTest.kt
Labels: Snake 🐍, Tech Debt

#1742 build(deps): Fix dependabot security vulnerabilities
  junit_html_report/package-lock.json
Labels: Bug, dependencies

#1735 docs: Add base pages for flank layers
  docs/refactor/steps.md
  mkdocs.yml
  test_runner/src/main/kotlin/ftl/README.md
  test_runner/src/main/kotlin/ftl/adapter/README.md
  test_runner/src/main/kotlin/ftl/cli/README.md
  test_runner/src/main/kotlin/ftl/data/README.md
  test_runner/src/main/kotlin/ftl/domain/README.md
  test_runner/src/main/kotlin/ftl/presentation/README.md
Labels: Documentation, Tech Debt
