Repository Flank/flank, pull requests merged in 2021-04, with the labels that each got.

#1765 docs: Add HLD for Test case based retries
  docs/feature/1692_test_case_based_retries.md
Labels: Feature, HLD, P1, Research, Tiger 🐯

#1739 feat: Windows IOS integration tests
  test_runner/src/main/kotlin/ftl/ios/xctest/common/InstallParseBinaries.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseObjTests.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseSwiftTests.kt
  test_runner/src/main/kotlin/ftl/util/Bash.kt
Labels: Feature, P2, Tiger 🐯

#1772 fix: Fix flank-scripts test failure on MacOS
  flank-scripts/build.gradle.kts
  flank-scripts/src/test/kotlin/flank/scripts/ops/testartifacts/TestArtifactsRepoTest.kt
Labels: Bug, Snake 🐍

#1782 fix: Fix entrypoint file name
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/Main.kt
  test_runner/src/test/kotlin/ftl/MainTest.kt
Labels: Bug, P0

#1784 fix: Skip Dump shards IT test
  integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
Labels: Bug, IT_Failed, Snake 🐍

#1779 feat: Implement custom sharding -- iOS
  docs/feature/1665-custom-sharding.md
  test_runner/src/main/kotlin/ftl/ios/xctest/XcTestData.kt
  test_runner/src/main/kotlin/ftl/run/DumpShards.kt
  test_runner/src/main/kotlin/ftl/util/ObfuscationGson.kt
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/custom_sharding_ios_v1.json
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/custom_sharding_ios_v2.json
  test_runner/src/test/kotlin/ftl/ios/xctest/XcTestDataTest.kt
  test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
Labels: Feature, New Option, Tiger 🐯

#1773 feat: Add printing total run duration
  test_runner/src/main/kotlin/ftl/Main.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestAndroid.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestIos.kt
  test_runner/src/main/kotlin/ftl/reports/DurationReport.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/main/kotlin/ftl/run/status/TestMatrixStatusPrinter.kt
  test_runner/src/main/kotlin/ftl/util/StopWatch.kt
  test_runner/src/main/kotlin/ftl/util/StopWatchMatrix.kt
  test_runner/src/test/kotlin/Debug.kt
  test_runner/src/test/kotlin/ftl/run/status/TestMatrixStatusPrinterTest.kt
  test_runner/src/test/kotlin/ftl/util/StopWatchTest.kt
  test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Labels: Feature, P1, Tiger 🐯

#1791 docs: Hypershard android usage guide
  docs/hypershard_android.md
  mkdocs.yml
Labels: Android, Documentation, P1, Research, Tiger 🐯

#1793 fix: Added workaround for uppercase project name
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/RefreshCommandTest.kt
Labels: Bug, P0

#1788 docs: Added hypershard-ios setup tutorial
  docs/hypershard_ios.md
  mkdocs.yml
Labels: Documentation, P1, Research, Tiger 🐯, iOS

#1805 docs: Fix information about project id
  docs/index.md
  test_runner/flank.ios.yml
  test_runner/flank.yml
Labels: Bug

#1783 test: Add 3dmark instrumented test
  common/src/main/kotlin/flank/common/PathHelper.kt
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ops/assemble/android/BuildBenchmark.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/assemble/android/RunAndroidOps.kt
  test_projects/android/benchmark/README.md
  test_projects/android/benchmark/build.gradle
  test_projects/android/benchmark/proguard-rules.pro
  test_projects/android/benchmark/src/androidTest/java/com/example/test/benchmark/Run3DMark.kt
  test_projects/android/benchmark/src/androidTest/java/com/example/test/benchmark/RunGeekbench.kt
  test_projects/android/benchmark/src/androidTest/java/com/example/test/benchmark/RunPassMark.kt
  test_projects/android/benchmark/src/main/AndroidManifest.xml
  test_projects/android/settings.gradle
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/3dmark-NexusLowRes.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/3dmark-NexusLowResEmulator.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/3dmark-all.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/3dmark-redfin.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/geekbench-NexusLowRes.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/geekbench-NexusLowResEmulator.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/geekbench-all.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/geekbench-redfin.yml
  test_runner/src/test/kotlin/ftl/fixtures/benchmark/passmark-all.yml
Labels: Dragon 🐲, P0, POC, Research

#1809 refactor: Refactor data scratch-authorization
  test_runner/src/main/kotlin/ftl/adapter/GoogleUserAuthorizationRequest.kt
  test_runner/src/main/kotlin/ftl/adapter/google/Credentials.kt
  test_runner/src/main/kotlin/ftl/adapter/google/UserAuth.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/data/UserAuthorization.kt
  test_runner/src/main/kotlin/ftl/domain/LoginGoogleAccount.kt
  test_runner/src/main/kotlin/ftl/gc/GcStorage.kt
  test_runner/src/main/kotlin/ftl/gc/GcTesting.kt
  test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
  test_runner/src/test/kotlin/ftl/adapter/google/UserAuthTest.kt
Labels: Refactor, Tiger 🐯

#1813 ci: Disabled estimations copying
  .github/workflows/pr_checks.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/github/CopyIssuePropertiesCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/github/CopyGitHubProperties.kt
Labels: Snake 🐍

#1807 fix: Fix missing junit report in legacy mode
  integration_tests/src/test/kotlin/integration/LegacyResultIT.kt
  integration_tests/src/test/resources/cases/flank_android_single_legacy.yml
  integration_tests/src/test/resources/cases/flank_ios_single_legacy.yml
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
Labels: Bug, Tiger 🐯

#1811 refactor: Refactor data scratch-ipblocks
  test_runner/src/main/kotlin/ftl/adapter/GoogleIpBlockFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/google/IpBlockAdapter.kt
  test_runner/src/main/kotlin/ftl/api/IpBlock.kt
  test_runner/src/main/kotlin/ftl/client/google/DeviceIpBlocks.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListIPBlocks.kt
  test_runner/src/main/kotlin/ftl/environment/IpBlocksToTable.kt
  test_runner/src/main/kotlin/ftl/environment/ListIPBlocks.kt
  test_runner/src/main/kotlin/ftl/gc/GcTesting.kt
  test_runner/src/test/kotlin/ftl/adapter/google/IpBlockAdapterTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ipblocks/IPBlocksListCommandTest.kt
Labels: Refactor, Tiger 🐯

#1820 refactor: Refactor data scratch-orientation
  test_runner/src/main/kotlin/ftl/adapter/GoogleOrientationFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/google/OrientationsAdapter.kt
  test_runner/src/main/kotlin/ftl/api/Orientation.kt
  test_runner/src/main/kotlin/ftl/args/PrepareAndroidCommonConfig.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidLocales.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidModels.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidVersions.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidLocales.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidModels.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidOrientations.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidVersions.kt
  test_runner/src/main/kotlin/ftl/domain/ListIosOrientations.kt
  test_runner/src/main/kotlin/ftl/environment/NetworkConfigurationCatalog.kt
  test_runner/src/main/kotlin/ftl/environment/android/ListAndroidDevices.kt
  test_runner/src/main/kotlin/ftl/environment/android/ListAndroidSofwareVersions.kt
  test_runner/src/main/kotlin/ftl/environment/common/ListNetworkConfiguration.kt
  test_runner/src/main/kotlin/ftl/environment/common/ListOrientations.kt
  test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
  test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
  test_runner/src/main/kotlin/ftl/reports/outcome/BillableMinutes.kt
  test_runner/src/test/kotlin/ftl/adapter/google/OrientationsAdapterTest.kt
  test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesDescribeCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesListCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/orientations/AndroidOrientationCommandListTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/versions/AndroidVersionsDescribeCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/orientations/IosOrientationCommandListTest.kt
  test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
  test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
Labels: Refactor, Tiger 🐯

#1829 fix: CI issues on ubuntu
  .github/workflows/ubuntu-workflow.yml
Labels: Bug, Snake 🐍

#1825 test: Optimize quota usage in IT
  integration_tests/build.gradle.kts
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  integration_tests/src/test/kotlin/integration/CustomShardingIT.kt
  integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
  integration_tests/src/test/kotlin/integration/GameloopIT.kt
  integration_tests/src/test/kotlin/integration/IgnoreFailedIT.kt
  integration_tests/src/test/kotlin/integration/LegacyResultIT.kt
  integration_tests/src/test/kotlin/integration/ManyTestsOnSingleShardIT.kt
  integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
  integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt
  integration_tests/src/test/kotlin/integration/RunTimeoutIT.kt
  integration_tests/src/test/kotlin/integration/SanityRoboIT.kt
  integration_tests/src/test/kotlin/integration/TestFilteringIT.kt
  integration_tests/src/test/kotlin/integration/config/Categories.kt
Labels: Tech Debt

#1819 refactor: Refactor data scratch network profiles
  test_runner/src/main/kotlin/ftl/adapter/NetworkProfileFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/google/NetworkProfileAdapter.kt
  test_runner/src/main/kotlin/ftl/api/NetworkProfile.kt
  test_runner/src/main/kotlin/ftl/client/google/GoogleNetworkProfileFetch.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListNetworkProfiles.kt
  test_runner/src/main/kotlin/ftl/environment/NetworkConfigurationCatalog.kt
  test_runner/src/main/kotlin/ftl/environment/NetworkProfileDescription.kt
  test_runner/src/main/kotlin/ftl/environment/common/ListNetworkConfiguration.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfileDescribeTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesListCommandTest.kt
Labels: Refactor, Tiger 🐯

#1824 feat: Instrument test console log parser
  corellium/log/build.gradle.kts
  corellium/log/src/main/kotlin/flank/corellium/log/Internal.kt
  corellium/log/src/main/kotlin/flank/corellium/log/Parser.kt
  corellium/log/src/test/kotlin/flank/corellium/log/InternalTest.kt
  corellium/log/src/test/resources/example_android_logs.txt
  settings.gradle.kts
Labels: Corellium, Tiger 🐯

#1810 refactor: Refactor data scratch-remote storage
  test_runner/src/main/kotlin/ftl/adapter/GcStorageExists.kt
  test_runner/src/main/kotlin/ftl/adapter/GcStorageUpload.kt
  test_runner/src/main/kotlin/ftl/api/RemoteStorage.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/ValidateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt
  test_runner/src/main/kotlin/ftl/client/google/GcStorageAdapter.kt
  test_runner/src/main/kotlin/ftl/reports/CostReport.kt
  test_runner/src/main/kotlin/ftl/reports/FullJUnitReport.kt
  test_runner/src/main/kotlin/ftl/reports/HtmlErrorReport.kt
  test_runner/src/main/kotlin/ftl/reports/JUnitReport.kt
  test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt
  test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReport.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadOtherFiles.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/ios/CreateXcTestContext.kt
  test_runner/src/main/kotlin/ftl/util/FileReference.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/ArgsHelperTest.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/AndroidRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/IosRunCommandTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
  test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
  test_runner/src/test/kotlin/ftl/reports/output/OutputReportTest.kt
  test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
  test_runner/src/test/kotlin/ftl/test/util/LocalGcs.kt
Labels: Refactor, Tiger 🐯

#1823 refactor: Refactor data scratch-softwarecatalog
  test_runner/src/main/kotlin/ftl/adapter/GoogleProvidedSoftwareCatalog.kt
  test_runner/src/main/kotlin/ftl/adapter/google/SoftwareCatalogAdapter.kt
  test_runner/src/main/kotlin/ftl/api/SoftwareCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/ProvidedSoftwareCatalog.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListProvidedSoftware.kt
  test_runner/src/main/kotlin/ftl/environment/ProvidedSoftwareCatalog.kt
  test_runner/src/main/kotlin/ftl/environment/common/ListProvidedSoftware.kt
  test_runner/src/test/kotlin/ftl/environment/ListProvidedSoftwareTest.kt
Labels: Refactor, Tiger 🐯

#1834 refactor: Refactor data scratch-device model
  test_runner/src/main/kotlin/ftl/adapter/GoogleDeviceModel.kt
  test_runner/src/main/kotlin/ftl/adapter/google/DeviceModelAdapter.kt
  test_runner/src/main/kotlin/ftl/api/DeviceModels.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidModels.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosModels.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidModels.kt
  test_runner/src/main/kotlin/ftl/domain/ListIosModels.kt
  test_runner/src/main/kotlin/ftl/environment/TestEnvironmentInfo.kt
  test_runner/src/main/kotlin/ftl/environment/android/AndroidModelDescription.kt
  test_runner/src/main/kotlin/ftl/environment/android/ListAndroidDevices.kt
  test_runner/src/main/kotlin/ftl/environment/ios/IosModelDescription.kt
  test_runner/src/main/kotlin/ftl/environment/ios/ListIOsDevices.kt
  test_runner/src/main/kotlin/ftl/environment/ios/ListIOsSofwareVersions.kt
  test_runner/src/main/kotlin/ftl/ios/IosCatalog.kt
  test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
  test_runner/src/test/kotlin/ftl/args/SupportedDeviceConfigTest.kt
  test_runner/src/test/kotlin/ftl/args/ValidateIosArgsTest.kt
  test_runner/src/test/kotlin/ftl/environment/android/AndroidModelDescriptionTest.kt
  test_runner/src/test/kotlin/ftl/environment/ios/IosModelDescriptionTest.kt
  test_runner/src/test/kotlin/ftl/ios/IosCatalogTest.kt
Labels: Refactor, Tiger 🐯

#1833 refactor: Refactor os versions commands
  test_runner/src/main/kotlin/ftl/adapter/AndroidOsVersionsFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/IosVersionsFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/google/AndroidOsVersions.kt
  test_runner/src/main/kotlin/ftl/adapter/google/IosOsVersions.kt
  test_runner/src/main/kotlin/ftl/api/OsVersion.kt
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/OsVersion.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidVersions.kt
  test_runner/src/main/kotlin/ftl/environment/android/AndroidSoftwareVersionDescription.kt
  test_runner/src/main/kotlin/ftl/environment/android/ListAndroidSofwareVersions.kt
  test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
  test_runner/src/test/kotlin/ftl/environment/android/AndroidSoftwareVersionDescriptionTest.kt
Labels: Refactor, Tiger 🐯

#1840 refactor: Refactor data scratch-performance metrics
  test_runner/src/main/kotlin/ftl/adapter/GooglePerformanceMetricsFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/google/PerfMetricsAdapter.kt
  test_runner/src/main/kotlin/ftl/api/PerfMetrics.kt
  test_runner/src/main/kotlin/ftl/gc/GcToolResults.kt
  test_runner/src/main/kotlin/ftl/reports/api/PerformanceMetrics.kt
  test_runner/src/main/kotlin/ftl/util/StopWatch.kt
  test_runner/src/test/kotlin/ftl/adapter/google/PerfMetricsAdapterTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcStorageTest.kt
  test_runner/src/test/kotlin/ftl/reports/api/PerformanceMetricsTest.kt
Labels: Refactor, Tiger 🐯

#1842 test: Update task ordering
  integration_tests/build.gradle.kts
Labels: Bug, IT_Failed, Snake 🐍

#1828 refactor: data scratch getLocales
  test_runner/src/main/kotlin/ftl/adapter/GoogleDeviceModel.kt
  test_runner/src/main/kotlin/ftl/adapter/GoogleLocalesFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/GoogleOrientationFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/google/LocalesAdapter.kt
  test_runner/src/main/kotlin/ftl/api/Locale.kt
  test_runner/src/main/kotlin/ftl/api/Orientation.kt
  test_runner/src/main/kotlin/ftl/api/Platform.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidLocales.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosLocales.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosModels.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosVersions.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidLocales.kt
  test_runner/src/main/kotlin/ftl/domain/ListIosLocales.kt
  test_runner/src/main/kotlin/ftl/domain/ListIosVersions.kt
  test_runner/src/main/kotlin/ftl/environment/ListLocales.kt
  test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesDescribeCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/android/locales/AndroidLocalesListCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesDescribeCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/configuration/IosLocalesListCommandTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/orientations/IosOrientationCommandListTest.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/ios/versions/IosVersionsDescribeCommandTest.kt
  test_runner/src/test/kotlin/ftl/ios/IosCatalogTest.kt
Labels: Refactor, Tiger 🐯

#1835 feat: Add sharding implementation for corellium
  corellium/shard/README.md
  corellium/shard/build.gradle.kts
  corellium/shard/src/main/kotlin/flank/corellium/shard/Internal.kt
  corellium/shard/src/main/kotlin/flank/corellium/shard/Shard.kt
  corellium/shard/src/test/kotlin/flank/corellium/shard/ShardKtTest.kt
  docs/corellium/sharding-class.puml
  settings.gradle.kts
Labels: Corellium

#1879 feat: API layer for corellium MVP
  corellium/api/build.gradle.kts
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidApps.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidInstance.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidTestPlan.kt
  corellium/api/src/main/kotlin/flank/corellium/api/Authorization.kt
  corellium/api/src/main/kotlin/flank/corellium/api/CorelliumApi.kt
  corellium/api/src/main/kotlin/flank/corellium/api/Request.kt
  settings.gradle.kts
Labels: Corellium, Tiger 🐯

#1874 fix: Add storage dir support
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/test/kotlin/ftl/args/ValidateDirectoriesToPullAndroidArgsTest.kt
Labels: Bug

#1877 feat: TestApk parser
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  corellium/adapter/build.gradle.kts
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ParseTestApk.kt
  corellium/adapter/src/test/kotlin/flank/corellium/adapter/ParseTestApkTest.kt
  corellium/api/src/main/kotlin/flank/corellium/api/TestApk.kt
  settings.gradle.kts
  test_runner/build.gradle.kts
Labels: Corellium

#1878 refactor: corellium client to functional style
  corellium/client/src/main/kotlin/flank/corellium/client/Agent.kt
  corellium/client/src/main/kotlin/flank/corellium/client/Console.kt
  corellium/client/src/main/kotlin/flank/corellium/client/Corellium.kt
  corellium/client/src/main/kotlin/flank/corellium/client/VPN.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Agent.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Disconnect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/UploadFile.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Util.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Console.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Functions.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Api.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Corellium.kt
  corellium/client/src/main/kotlin/flank/corellium/client/data/DTOs.kt
  corellium/client/src/main/kotlin/flank/corellium/client/logging/LoggingLevel.kt
  corellium/client/src/main/kotlin/flank/corellium/client/util/Retry.kt
  corellium/sandbox/build.gradle.kts
  corellium/sandbox/src/main/kotlin/flank/corellium/sandbox/android/AndroidExample.kt
  corellium/sandbox/src/main/kotlin/flank/corellium/sandbox/android/AndroidExampleNoVPN.kt
  corellium/sandbox/src/main/kotlin/flank/corellium/sandbox/ios/ExampleCorelliumRun.kt
  docs/corellium/android-cli-domain-sequence.puml
  docs/corellium/android-domain-class.puml
  docs/corellium/client-api-class.puml
  docs/corellium/modules.puml
Labels: Corellium, Refactor

#1841 refactor: data scratch file references
  test_runner/src/main/kotlin/ftl/adapter/DownloadAsJunitXML.kt
  test_runner/src/main/kotlin/ftl/adapter/GcStorageDownload.kt
  test_runner/src/main/kotlin/ftl/adapter/google/FileReferenceAdapter.kt
  test_runner/src/main/kotlin/ftl/api/FileReference.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/client/google/FileReference.kt
  test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt
  test_runner/src/main/kotlin/ftl/client/google/GcStorageAdapter.kt
  test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt
  test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidLoopConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateInstrumentationConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateRoboConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
  test_runner/src/main/kotlin/ftl/run/platform/ios/CreateGameloopTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/ios/CreateXcTestContext.kt
  test_runner/src/main/kotlin/ftl/util/FileReference.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Labels: Refactor, Tiger 🐯

#1883 fix: Fix release job
  .github/workflows/release.yml
Labels: Bug, Snake 🐍

#1885 refactor: Refactor DescribeNetworkProfiles logging
  test_runner/src/main/kotlin/ftl/api/NetworkProfile.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeNetworkProfiles.kt
  test_runner/src/main/kotlin/ftl/environment/NetworkProfileDescription.kt
  test_runner/src/main/kotlin/ftl/presentation/Output.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/networkprofiles/NetworkProfilesDescribeCommand.kt
Labels: Feature, Tiger 🐯
