Repository Flank/flank, pull requests merged in 2021-05, with the labels that each got.

#1880 feat: Corellium adapters
  corellium/.gitignore
  corellium/adapter/build.gradle.kts
  corellium/adapter/src/main/kotlin/flank/corellium/Api.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ClientReference.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InstallAndroidApps.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InvokeAndroidDevices.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/RequestAuthorization.kt
  corellium/adapter/src/test/kotlin/flank/corellium/adapter/Example.kt
  corellium/adapter/src/test/resources/corellium.properties_template
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/UploadFile.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Functions.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Api.kt
  corellium/client/src/main/kotlin/flank/corellium/client/data/DTOs.kt
  corellium/sandbox/src/main/kotlin/flank/corellium/sandbox/android/AndroidExampleNoVPN.kt
  corellium/shard/README.md
Labels: Corellium

#1887 refactor: Structural output Android models describe
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidModels.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/models/AndroidModelDescribeCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/models/describe/AndroidModelDescription.kt
  test_runner/src/test/kotlin/ftl/environment/android/AndroidModelDescriptionTest.kt
Labels: Feature, Tiger 🐯

#1894 refactor: list android locales
  test_runner/src/main/kotlin/ftl/domain/ListAndroidLocales.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
Labels: Feature, Tiger 🐯

#1895 refactor: Structural output iOS models describe
  test_runner/src/main/kotlin/ftl/domain/DescribeIosModels.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/models/IosModelDescribeCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/models/describe/IosModelDescription.kt
  test_runner/src/test/kotlin/ftl/environment/ios/IosModelDescriptionTest.kt
Labels: Feature, Tiger 🐯

#1886 refactor: Describe ios locales
  test_runner/src/main/kotlin/ftl/api/Locale.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidLocales.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosLocales.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListIosLocales.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/configuration/IosLocalesDescribeCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/locale/ListLocales.kt
  test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
  test_runner/src/test/kotlin/ftl/ios/IosCatalogTest.kt
Labels: Feature, Refactor, Tiger 🐯

#1899 refactor: Android locales describes
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidLocales.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesDescribeCommand.kt
Labels: Feature, Refactor, Tiger 🐯

#1875 refactor: Fetching artifacts
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/adapter/GcFetchArtifacts.kt
  test_runner/src/main/kotlin/ftl/adapter/google/FetchArtifacts.kt
  test_runner/src/main/kotlin/ftl/api/Artifacts.kt
  test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt
  test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt
  test_runner/src/main/kotlin/ftl/run/NewTestRun.kt
  test_runner/src/main/kotlin/ftl/run/RefreshLastRun.kt
  test_runner/src/main/kotlin/ftl/run/common/FetchAllArtifacts.kt
  test_runner/src/main/kotlin/ftl/run/common/FetchArtifacts.kt
  test_runner/src/test/kotlin/ftl/run/TestRunnerTest.kt
  test_runner/src/test/kotlin/ftl/test/util/FlankTestRunner.kt
  test_runner/src/test/kotlin/ftl/test/util/LocalGcs.kt
Labels: Refactor, Tiger 🐯

#1896 refactor: Logging refactor - android/ios test environment
  test_runner/src/main/kotlin/ftl/adapter/GoogleTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/api/OsVersion.kt
  test_runner/src/main/kotlin/ftl/api/TestEnvironment.kt
  test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/environment/ios/ListIOsSofwareVersions.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/AndroidTestEnvironmentCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/IosTestEnvironmentCommand.kt
Labels: Feature, Tiger 🐯

#1900 fix: Several minor issues in corellium scope
  corellium/adapter/src/main/kotlin/flank/corellium/Api.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InstallAndroidApps.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InvokeAndroidDevices.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ParseApk.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ParseTestApk.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/RequestAuthorization.kt
  corellium/adapter/src/test/kotlin/flank/corellium/adapter/Example.kt
  corellium/adapter/src/test/kotlin/flank/corellium/adapter/ParseApkTest.kt
  corellium/adapter/src/test/kotlin/flank/corellium/adapter/ParseTestApkTest.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidApps.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidInstance.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidTestPlan.kt
  corellium/api/src/main/kotlin/flank/corellium/api/Apk.kt
  corellium/api/src/main/kotlin/flank/corellium/api/Authorization.kt
  corellium/api/src/main/kotlin/flank/corellium/api/CorelliumApi.kt
  corellium/api/src/main/kotlin/flank/corellium/api/Request.kt
  corellium/api/src/main/kotlin/flank/corellium/api/TestApk.kt
  corellium/client/build.gradle.kts
  corellium/client/src/main/kotlin/flank/corellium/client/console/Functions.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Corellium.kt
  corellium/client/src/test/kotlin/flank/corellium/client/parser/FunctionsKtTest.kt
  corellium/log/src/main/kotlin/flank/corellium/log/Internal.kt
  corellium/log/src/main/kotlin/flank/corellium/log/Parser.kt
  corellium/log/src/test/kotlin/flank/corellium/log/InternalTest.kt
  corellium/log/src/test/kotlin/flank/corellium/log/Util.kt
  corellium/log/src/test/resources/example_android_logs_0.txt
  corellium/log/src/test/resources/example_android_logs_1.txt
  corellium/log/src/test/resources/example_android_logs_2.txt
  corellium/log/src/test/resources/example_android_logs_3.txt
  corellium/shard/src/main/kotlin/flank/corellium/shard/Shard.kt
Labels: Corellium

#1902 refactor: Structural output cancel last run
  test_runner/src/main/kotlin/ftl/domain/CancelLastRun.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/CancelCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/MatrixCancelStatusMapper.kt
  test_runner/src/main/kotlin/ftl/run/CancelLastRun.kt
  test_runner/src/test/kotlin/ftl/util/UtilsTest.kt
Labels: Feature, Tiger 🐯

#1910 refactor: Structural output for iOS model list
  test_runner/src/main/kotlin/ftl/adapter/GoogleDeviceModel.kt
  test_runner/src/main/kotlin/ftl/adapter/GoogleTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/api/DeviceModels.kt
  test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosModels.kt
  test_runner/src/main/kotlin/ftl/domain/ListIosModels.kt
  test_runner/src/main/kotlin/ftl/environment/ios/ListIOsDevices.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/models/IosModelsListCommand.kt
Labels: Feature, Tiger 🐯

#1912 refactor: Move files for authentication data refactor
  test_runner/src/main/kotlin/ftl/adapter/GooglePerformanceMetricsFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/GoogleUserAuthorizationRequest.kt
  test_runner/src/main/kotlin/ftl/api/UserAuthorization.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/Credentials.kt
  test_runner/src/main/kotlin/ftl/client/google/DeviceIpBlocks.kt
  test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt
  test_runner/src/main/kotlin/ftl/client/google/GcTestMatrix.kt
  test_runner/src/main/kotlin/ftl/client/google/GcTesting.kt
  test_runner/src/main/kotlin/ftl/client/google/GcToolResults.kt
  test_runner/src/main/kotlin/ftl/client/google/GoogleNetworkProfileFetch.kt
  test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/OsVersion.kt
  test_runner/src/main/kotlin/ftl/client/google/ProvidedSoftwareCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/TestOutcomeContext.kt
  test_runner/src/main/kotlin/ftl/client/google/UserAuth.kt
  test_runner/src/main/kotlin/ftl/client/junit/CreateTestExecutionData.kt
  test_runner/src/main/kotlin/ftl/domain/LoginGoogleAccount.kt
  test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/BeforeRunTests.kt
  test_runner/src/test/kotlin/ftl/adapter/google/UserAuthTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/gc/GcToolResultsTest.kt
  test_runner/src/test/kotlin/ftl/reports/api/CreateTestExecutionDataKtTest.kt
  test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
  test_runner/src/test/kotlin/task/UpdateCatalogFixtures.kt
Labels: Refactor, Snake 🐍

#1916 refactor: Ip blocks output
  test_runner/src/main/kotlin/ftl/adapter/GoogleIpBlockFetch.kt
  test_runner/src/main/kotlin/ftl/adapter/google/IpBlockAdapter.kt
  test_runner/src/main/kotlin/ftl/api/IpBlock.kt
  test_runner/src/main/kotlin/ftl/api/TestEnvironment.kt
  test_runner/src/main/kotlin/ftl/domain/ListIPBlocks.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ipblocks/IPBlocksListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ipblocks/IpBlocksToTable.kt
  test_runner/src/test/kotlin/ftl/adapter/google/IpBlockAdapterTest.kt
  test_runner/src/test/kotlin/ftl/adapter/google/OrientationsAdapterTest.kt
Labels: Feature, Tiger 🐯

#1914 refactor: iOS List locales
  test_runner/src/main/kotlin/ftl/domain/ListIosLocales.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/configuration/IosLocalesListCommand.kt
Labels: Feature, Refactor, Tiger 🐯

#1907 refactor: Structural output for list android models
  test_runner/src/main/kotlin/ftl/adapter/GoogleDeviceModel.kt
  test_runner/src/main/kotlin/ftl/adapter/GoogleTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/api/DeviceModels.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeAndroidModels.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidModels.kt
  test_runner/src/main/kotlin/ftl/environment/android/ListAndroidDevices.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/models/AndroidModelsListCommand.kt
  test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
Labels: Feature, Tiger 🐯

#1908 feat: Add junit module
  corellium/junit/build.gradle.kts
  corellium/junit/src/main/kotlin/flank/junit/JUnit.kt
  corellium/junit/src/main/kotlin/flank/junit/mapper/Structural.kt
  corellium/junit/src/main/kotlin/flank/junit/mapper/Xml.kt
  corellium/junit/src/test/kotlin/flank/junit/FailOnInvalidJUnitReport.kt
  corellium/junit/src/test/kotlin/flank/junit/GenerateJUnitReport.kt
  corellium/junit/src/test/kotlin/flank/junit/ParseAndFormatJUnitReport.kt
  corellium/junit/src/test/kotlin/flank/junit/ParseEmptyJUnitReport.kt
  corellium/junit/src/test/kotlin/flank/junit/Util.kt
  corellium/junit/src/test/resources/JUnit.xsd
  corellium/junit/src/test/resources/JUnitReport.xml
  corellium/junit/src/test/resources/JUnitReport_empty_1.xml
  corellium/junit/src/test/resources/JUnitReport_empty_2.xml
  corellium/junit/src/test/resources/JUnitReport_empty_3.xml
  corellium/junit/src/test/resources/JUnitReport_invalid.xml
  settings.gradle.kts
Labels: Corellium

#1919 refactor: Structural output list provided software
  test_runner/src/main/kotlin/ftl/client/google/ProvidedSoftwareCatalog.kt
  test_runner/src/main/kotlin/ftl/domain/ListProvidedSoftware.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/orientations/AndroidOrientationsListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/providedsoftware/ListProvidedSoftware.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/providedsoftware/ProvidedSoftwareListCommand.kt
  test_runner/src/test/kotlin/ftl/environment/ListProvidedSoftwareTest.kt
Labels: Feature, Tiger 🐯

#1918 ci: Update wrong ubuntu variable name
  .github/workflows/full_suite_integration_tests.yml
Labels: Snake 🐍

#1915 refactor: Structural output list network profiles
  test_runner/src/main/kotlin/ftl/domain/ListNetworkProfiles.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/locales/AndroidLocalesListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/orientations/AndroidOrientationsListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/configuration/IosLocalesDescribeCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/configuration/IosLocalesListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/orientations/IosOrientationsListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/networkprofiles/ListNetworkConfiguration.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/networkprofiles/NetworkProfilesListCommand.kt
  test_runner/src/main/kotlin/ftl/util/CastingUtils.kt
  test_runner/src/test/kotlin/ftl/cli/firebase/test/networkprofiles/NetworkProfilesListCommandTest.kt
Labels: Feature, Refactor, Tiger 🐯

#1924 refactor: Structural output list ios versions
  test_runner/src/main/kotlin/ftl/adapter/GoogleTestEnvironment.kt
  test_runner/src/main/kotlin/ftl/adapter/IosVersionsFetch.kt
  test_runner/src/main/kotlin/ftl/api/OsVersion.kt
  test_runner/src/main/kotlin/ftl/domain/DescribeIosVersions.kt
  test_runner/src/main/kotlin/ftl/domain/ListIosVersions.kt
  test_runner/src/main/kotlin/ftl/environment/ios/ListIOsSofwareVersions.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/versions/IosVersionsListCommand.kt
Labels: Feature, Tiger 🐯

#1927 ci: Remaining ubuntu-latest variables
  .github/workflows/full_suite_integration_tests.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/integrationtests/ProcessResultCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/ProcessIntegrationTestsResult.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt
Labels: Snake 🐍, Tech Debt

#1921 feat: Dump shards
  corellium/shard/dump/README.md
  corellium/shard/dump/build.gradle.kts
  corellium/shard/dump/src/main/kotlin/flank/corellium/shard/Dump.kt
  corellium/shard/dump/src/main/kotlin/flank/corellium/shard/Internal.kt
  corellium/shard/dump/src/test/kotlin/flank/corellium/shard/DumpTest.kt
  settings.gradle.kts
Labels: Corellium

#1933 fix: Remove deprecated corellium adapters example
  corellium/adapter/src/test/kotlin/flank/corellium/adapter/Example.kt
  corellium/adapter/src/test/resources/corellium.properties_template
Labels: Corellium

#1934 ci: Make IT results independent of os versions
  .github/workflows/full_suite_integration_tests.yml
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/IntegrationResultContext.kt
Labels: Snake 🐍, Tech Debt

#1930 refactor: list android versions
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/domain/ListAndroidVersions.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/versions/AndroidVersionsListCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/versions/ListAndroidSofwareVersions.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/environment/TestEnvironmentInfo.kt
  test_runner/src/test/kotlin/ftl/android/AndroidCatalogTest.kt
Labels: Feature, Refactor, Tiger 🐯

#1923 feat: Obfuscate shards
  corellium/shard/README.md
  corellium/shard/obfuscate/README.md
  corellium/shard/obfuscate/build.gradle.kts
  corellium/shard/obfuscate/src/main/kotlin/flank/corellium/shard/Internal.kt
  corellium/shard/obfuscate/src/main/kotlin/flank/corellium/shard/Obfuscate.kt
  corellium/shard/obfuscate/src/test/kotlin/flank/corellium/shard/ObfuscateTest.kt
  corellium/shard/src/main/kotlin/flank/corellium/shard/Shard.kt
  settings.gradle.kts
Labels: Corellium

#1935 feat: Public API of corellium domain layer
  corellium/domain/build.gradle.kts
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestAndroidCorellium.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/util/Transform.kt
  settings.gradle.kts
Labels: Corellium

#1936 fix: Several minor corellium changes - part 2.
  corellium/junit/build.gradle.kts
  corellium/junit/src/main/kotlin/flank/junit/JUnit.kt
  corellium/junit/src/main/kotlin/flank/junit/mapper/JacksonXml.kt
  corellium/junit/src/test/kotlin/flank/junit/FailOnInvalidJUnitReportTest.kt
  corellium/junit/src/test/kotlin/flank/junit/GenerateJUnitReportTest.kt
  corellium/junit/src/test/kotlin/flank/junit/ParseAndFormatJUnitReport.kt
  corellium/junit/src/test/kotlin/flank/junit/ParseEmptyJUnitReportTest.kt
  corellium/junit/src/test/kotlin/flank/junit/ParseJUnitReportTest.kt
  corellium/log/src/main/kotlin/flank/corellium/log/Internal.kt
  corellium/log/src/main/kotlin/flank/corellium/log/Parser.kt
  corellium/shard/calculate/src/main/kotlin/flank/corellium/shard/CalculateShards.kt
  corellium/shard/calculate/src/test/kotlin/flank/corellium/shard/CalculateShardsTest.kt
  corellium/shard/dump/src/main/kotlin/flank/corellium/shard/Dump.kt
  corellium/shard/dump/src/main/kotlin/flank/corellium/shard/mapper/GsonJson.kt
  corellium/shard/dump/src/test/kotlin/flank/corellium/shard/DumpTest.kt
Labels: Corellium

#1940 feat: Corellium MVP CLI layer
  corellium/cli/build.gradle.kts
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/util/Config.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestAndroidCorellium.kt
  settings.gradle.kts
Labels: Corellium

#1943 fix: Several minor corellium changes - part 3.
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/domain/build.gradle.kts
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumExample.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestParsingAndroid.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/Utils.kt
Labels: Corellium

#1942 ci: Ubuntu updates
  .github/workflows/full_suite_integration_tests.yml
  .github/workflows/release.yml
  .github/workflows/ubuntu-workflow.yml
  .github/workflows/wsl-workflow.yml
  docs/windows_wsl_guide.md
Labels: Bug

#1945 feat: Integrate flank.jar with corellium CLI
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/presentation/cli/CorelliumCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/MainCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/corellium/TestCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/corellium/test/AndroidCommand.kt
  test_runner/src/test/kotlin/ftl/MainTest.kt
Labels: Corellium

#1947 feat: added max-test-shards and client-details to additional-app-test-apks
  test_runner/src/main/kotlin/ftl/api/TestAndroidMatrix.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/AppTestPair.kt
  test_runner/src/main/kotlin/ftl/client/google/run/android/GcAndroidTestMatrix.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidFlankConfig.kt
  test_runner/src/main/kotlin/ftl/mock/MockServer.kt
  test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestMatrixType.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsFileTest.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-mixed.yml
  test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Labels: Tiger 🐯

#1897 feat: Domain layer implementation for android test run Corellium MVP
  corellium/domain/README.md
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Authorize.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CleanUpInstances.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CreateOutputDir.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/DumpShards.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Finish.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/GenerateReport.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InstallApks.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InvokeDevices.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseApkInfo.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseTestCases.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/PrepareShards.kt
  docs/corellium/steps-dependencies-class.puml
Labels: Corellium

#1948 refactor: Move am instrument commad formatter to dedicated module
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidTestPlan.kt
  corellium/domain/build.gradle.kts
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/GenerateReport.kt
  corellium/instrument/command/build.gradle.kts
  corellium/instrument/command/src/main/kotlin/flank/instrument/command/FormatAmInstrumentCommand.kt
  corellium/instrument/command/src/test/kotlin/flank/instrument/command/FormatAmInstrumentCommandKtTest.kt
  corellium/instrument/log/build.gradle.kts
  corellium/instrument/log/src/main/kotlin/flank/instrument/log/Internal.kt
  corellium/instrument/log/src/main/kotlin/flank/instrument/log/Parser.kt
  corellium/instrument/log/src/test/kotlin/flank/instrument/log/InternalTest.kt
  corellium/instrument/log/src/test/kotlin/flank/instrument/log/Util.kt
  corellium/instrument/log/src/test/resources/example_android_logs_0.txt
  corellium/instrument/log/src/test/resources/example_android_logs_1.txt
  corellium/instrument/log/src/test/resources/example_android_logs_2.txt
  corellium/instrument/log/src/test/resources/example_android_logs_3.txt
  settings.gradle.kts
Labels: Corellium, Refactor

#1954 docs: Add architecture abstraction
  docs/architecture.md
  docs/hld/architecture-template.puml
  mkdocs.yml
Labels: Documentation

#1937 refactor: Run doctor command
  test_runner/src/main/kotlin/ftl/doctor/Doctor.kt
  test_runner/src/main/kotlin/ftl/domain/RunDoctor.kt
  test_runner/src/main/kotlin/ftl/domain/RunDoctorAndroid.kt
  test_runner/src/main/kotlin/ftl/domain/RunDoctorIos.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/CommandUtil.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/AndroidDoctorCommand.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ios/IosDoctorCommand.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/test/kotlin/ftl/doctor/DoctorTest.kt
Labels: Feature, Tiger 🐯

#1949 ci: Validate Maven version on publish
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Plugins.kt
  maven_version_check/build.gradle.kts
  maven_version_check/settings.gradle.kts
  maven_version_check/src/main/kotlin/MavenVersionCheck.kt
  maven_version_check/src/test/kotlin/MavenVersionCheckTest.kt
  settings.gradle.kts
  test_runner/build.gradle.kts
Labels: Feature, P0, Tiger 🐯

#1956 fix: annotation filtering for parameterized classes
  test_projects/android/apks/app-Large-Parameterized.apk
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Labels: Snake 🐍

#1952 refactor: data scratch ios
  integration_tests/src/test/kotlin/integration/AllTestFilteredIT.kt
  test_runner/src/main/kotlin/ftl/adapter/GoogleTestMatrixIos.kt
  test_runner/src/main/kotlin/ftl/api/TestMatrixIOS.kt
  test_runner/src/main/kotlin/ftl/client/google/run/ios/GcIosDevice.kt
  test_runner/src/main/kotlin/ftl/client/google/run/ios/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/client/google/run/ios/SetupIosTest.kt
  test_runner/src/main/kotlin/ftl/gc/GcIosTestMatrix.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunIosTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/ios/CreateIosTestConfig.kt
  test_runner/src/main/kotlin/ftl/run/platform/ios/CreateIosTestMatrixType.kt
  test_runner/src/test/kotlin/ftl/gc/GcIosTestMatrixTest.kt
Labels: Refactor, Tiger 🐯

#1965 build: update kotlin to 1.5.10 and remove warnings
  buildSrc/src/main/kotlin/Versions.kt
  common/src/main/kotlin/flank/common/Os.kt
  corellium/adapter/build.gradle.kts
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InvokeAndroidDevices.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Api.kt
  corellium/shard/calculate/src/test/kotlin/flank/corellium/shard/CalculateShardsTest.kt
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/ops/common/GenerateChangeLog.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/integrationtests/common/ITResult.kt
  flank-scripts/src/test/kotlin/flank/scripts/utils/VersionParseTest.kt
  integration_tests/src/test/kotlin/integration/CustomShardingIT.kt
  integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
  integration_tests/src/test/kotlin/integration/MultipleDevicesIT.kt
  integration_tests/src/test/kotlin/utils/OutputHelper.kt
  test_runner/build.gradle.kts
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
  test_runner/src/main/kotlin/ftl/args/CreateCommonArgs.kt
  test_runner/src/main/kotlin/ftl/args/IosArgs.kt
  test_runner/src/main/kotlin/ftl/client/junit/CreateTestSuiteOverviewData.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReportType.kt
  test_runner/src/main/kotlin/ftl/run/status/OutputStyle.kt
  test_runner/src/main/kotlin/ftl/shard/ShardCount.kt
  test_runner/src/main/kotlin/ftl/util/Utils.kt
  test_runner/src/test/kotlin/ftl/shard/ShardTest.kt
Labels: Feature, Tiger 🐯, dependencies

#1967 fix: Filter devices without supported versions
  test_runner/src/main/kotlin/ftl/client/google/AndroidCatalog.kt
  test_runner/src/main/kotlin/ftl/client/google/IosCatalog.kt
  test_runner/src/test/kotlin/ftl/args/IosArgsTest.kt
  test_runner/src/test/kotlin/ftl/args/ValidateIosArgsTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/android_catalog.json
  test_runner/src/test/kotlin/ftl/fixtures/ios_catalog.json
  test_runner/src/test/kotlin/ftl/reports/outcome/BillableMinutesTest.kt
Labels: Bug, Tiger 🐯

#1961 docs: Add implementation section to architecture doc
  docs/architecture.md
  docs/hld/horizontal-composition-layered.puml
  docs/hld/horizontal-composition.puml
  docs/hld/vertical-composition.puml
Labels: Documentation

#1970 feat: Add test file column to result table
  integration_tests/src/test/kotlin/utils/OutputReportParser.kt
  test_runner/src/main/kotlin/ftl/adapter/google/GoogleTestMatrixAdapter.kt
  test_runner/src/main/kotlin/ftl/api/TestMatrix.kt
  test_runner/src/main/kotlin/ftl/domain/testmatrix/UpdateTestMatrix.kt
  test_runner/src/main/kotlin/ftl/json/SavedMatrixTableUtil.kt
  test_runner/src/main/kotlin/ftl/reports/output/OutputReportLoggers.kt
  test_runner/src/test/kotlin/ftl/reports/output/OutputReportLoggersTest.kt
Labels: Bug, P0, Tiger 🐯

#1968 feat: added support for JUnit Theory tests
  test_projects/android/apks/app-theory-androidTest.apk
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
Labels: Snake 🐍

#1972 ci: update cla assitant
  .github/workflows/cla.yml
Labels: Bug, Tiger 🐯

#1982 fix: CIOEngineContainer not found
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Connect.kt
  test_configs/.gitignore
  test_configs/flank-corellium.yml
Labels: Bug, Corellium, P0

#1981 fix: Enable dump shards IT
  integration_tests/src/test/kotlin/integration/DumpShardsIT.kt
Labels: Bug, Snake 🐍

#1969 docs: Add docs for Corellium modules
  corellium/README.md
  corellium/adapter/README.md
  corellium/api/README.md
  corellium/apk/README.md
  corellium/apk/src/main/kotlin/flank/apk/internal/Parse.kt
  corellium/cli/README.md
  corellium/client/README.md
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Agent.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Disconnect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/UploadFile.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Api.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Console.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Api.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/core/Corellium.kt
  corellium/client/src/test/kotlin/flank/corellium/client/console/ApiKtTest.kt
  corellium/domain/README.md
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/instrument/README.md
  corellium/instrument/command/README.md
  corellium/instrument/command/src/main/kotlin/flank/instrument/command/FormatAmInstrumentCommand.kt
  corellium/instrument/log/README.md
  corellium/instrument/log/src/main/kotlin/flank/instrument/log/Internal.kt
  corellium/instrument/log/src/main/kotlin/flank/instrument/log/Parser.kt
  corellium/instrument/log/src/test/kotlin/flank/instrument/log/InternalTest.kt
  corellium/junit/README.md
  corellium/sandbox/src/main/kotlin/flank/corellium/sandbox/android/AndroidExample.kt
  corellium/shard/README.md
  corellium/shard/calculate/README.md
  corellium/shard/dump/README.md
  corellium/shard/obfuscate/README.md
  docs/corellium/client-api-class.puml
  docs/corellium/modules.puml
  docs/corellium/run-test-android.puml
  docs/corellium/steps-dependencies-class.puml
Labels: Corellium, Documentation

#1977 docs: Add user guide for Corellium MVP
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  docs/flank_corellium.md
  mkdocs.yml
Labels: Corellium, Documentation, Tiger 🐯
