Repository Flank/flank, pull requests merged in 2021-06, with the labels that each got.

#1991 feat: Enable GPU acceleration for new instances
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InvokeAndroidDevices.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidInstance.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/client/src/main/kotlin/flank/corellium/client/data/DTOs.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InvokeDevices.kt
Labels: Corellium, Feature, P0, Tiger 🐯

#1992 feat: Disable window animation in tests by default
  corellium/instrument/command/src/main/kotlin/flank/instrument/command/FormatAmInstrumentCommand.kt
  corellium/instrument/command/src/test/kotlin/flank/instrument/command/FormatAmInstrumentCommandKtTest.kt
Labels: Corellium, Feature, P0

#1994 fix: Disable ASCII doc generation (release blocker)
  .github/workflows/release_notes_generation.yml
Labels: Bug, P0

#1998 feat: Load test cases durations from previous run and use for sharding
  corellium/cli/build.gradle.kts
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/GenerateReport.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/LoadPreviousDurations.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/PrepareShards.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumExample.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestParsingAndroid.kt
  corellium/junit/src/main/kotlin/flank/junit/JUnit.kt
  corellium/junit/src/main/kotlin/flank/junit/internal/CalculateMedianDurations.kt
  corellium/junit/src/main/kotlin/flank/junit/internal/ParseJUnitTestResults.kt
  corellium/junit/src/main/kotlin/flank/junit/mapper/JacksonXml.kt
  corellium/junit/src/main/kotlin/flank/junit/mapper/ParseJUnitReport.kt
  corellium/junit/src/main/kotlin/flank/junit/mapper/Structural.kt
  corellium/junit/src/test/kotlin/flank/junit/GenerateJUnitReportTest.kt
  corellium/junit/src/test/kotlin/flank/junit/Util.kt
  corellium/junit/src/test/kotlin/flank/junit/internal/CalculateMedianDurationsKtTest.kt
  corellium/junit/src/test/kotlin/flank/junit/mapper/FailOnInvalidJUnitReportTest.kt
  corellium/junit/src/test/kotlin/flank/junit/mapper/ParseEmptyJUnitReportTest.kt
  corellium/junit/src/test/kotlin/flank/junit/mapper/ParseJUnitReportTest.kt
  corellium/junit/src/test/kotlin/flank/junit/mapper/StructuralKtTest.kt
  docs/flank_corellium.md
Labels: Corellium, Feature, Tiger 🐯

#2005 Fix: bucket not found but can't be created
  test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt
Labels: Bug, Snake 🐍

#2016 feat: Set Google api issues level as DEBUG
  test_runner/src/main/kotlin/ftl/http/ExecuteWithRetry.kt
  test_runner/src/main/kotlin/ftl/run/exception/ExceptionHandler.kt
  test_runner/src/main/kotlin/ftl/util/CrashReporter.kt
Labels: Feature, Research, Tiger 🐯

#2004 feat: Additional config options for test pairs
  docs/index.md
  integration_tests/src/test/kotlin/integration/MultipleApksIT.kt
  integration_tests/src/test/resources/cases/flank_android_multiple_apk.yml
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/adapter/GoogleTestMatrixAndroid.kt
  test_runner/src/main/kotlin/ftl/api/TestAndroidMatrix.kt
  test_runner/src/main/kotlin/ftl/args/ArgsToString.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/yml/AppTestPair.kt
  test_runner/src/main/kotlin/ftl/client/google/run/android/GcAndroidTestMatrix.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidFlankConfig.kt
  test_runner/src/main/kotlin/ftl/run/model/AndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestMatrixType.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/ResolveApks.kt
  test_runner/src/main/kotlin/ftl/run/platform/android/UploadApks.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
  test_runner/src/test/kotlin/ftl/fixtures/test_app_cases/flank-multiple-mixed.yml
  test_runner/src/test/kotlin/ftl/gc/GcAndroidTestMatrixTest.kt
  test_runner/src/test/kotlin/ftl/run/DumpShardsKtTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/RunAndroidTestsKtTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/CreateAndroidTestContextKtTest.kt
  test_runner/src/test/kotlin/ftl/run/platform/android/ResolveApksKtTest.kt
  test_runner/src/test/kotlin/ftl/test/util/TestHelper.kt
Labels: Feature, P0, Tiger 🐯

#2019 fix: Fix generating documentation
  test_runner/build.gradle.kts
Labels: Bug

#2026 fix: Fix flank freezes when large number of matrices is launched
  test_runner/src/main/kotlin/ftl/adapter/TestMatrixRefresh.kt
  test_runner/src/main/kotlin/ftl/api/TestMatrix.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
Labels: Bug, P0

#2031 fix: Bump up trim-newlines version
  junit_html_report/package-lock.json
  junit_html_report/package.json
Labels: Snake 🐍, Tech Debt

#2034 feat: Remove print lines from Corellium client
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Agent.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Connect.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/UploadFile.kt
  corellium/client/src/main/kotlin/flank/corellium/client/agent/Util.kt
  corellium/client/src/main/kotlin/flank/corellium/client/console/Api.kt
  corellium/client/src/main/kotlin/flank/corellium/client/util/Retry.kt
  corellium/sandbox/src/main/kotlin/flank/corellium/sandbox/android/AndroidExampleNoVPN.kt
Labels: Corellium, Feature

#2035 feat: Added new Parameterized Test Option
  build.gradle.kts
  docs/index.md
  test_runner/flank.yml
  test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/CreateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt
  test_runner/src/main/kotlin/ftl/config/FlankDefaults.kt
  test_runner/src/main/kotlin/ftl/config/android/AndroidGcloudConfig.kt
  test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt
Labels: Android, Feature, New Option, P1, Snake 🐍, Tiger 🐯

#2033 feat: Add tools for structural logging
  settings.gradle.kts
  tool/log/README.md
  tool/log/build.gradle.kts
  tool/log/format/README.md
  tool/log/format/build.gradle.kts
  tool/log/format/src/main/kotlin/flank/log/Builder.kt
  tool/log/format/src/main/kotlin/flank/log/Formatter.kt
  tool/log/format/src/test/kotlin/flank/log/LoggingTest.kt
  tool/log/src/main/kotlin/flank/log/Event.kt
  tool/log/src/main/kotlin/flank/log/Logger.kt
Labels: Corellium, Feature

#2009 feat: Implement tool for parallel execution
  docs/hld/parallel-example-graph.puml
  docs/hld/parallel-execution-api-functions.puml
  docs/hld/parallel-execution-api-structures.puml
  docs/hld/parallel-execution.puml
  docs/hld/task-graph.puml
  settings.gradle.kts
  tool/execution/parallel/README.md
  tool/execution/parallel/build.gradle.kts
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Create.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Execute.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Parallel.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Reduce.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/Validate.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/ContextProvider.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Execution.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Ext.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Prepare.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Property.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/Reduce.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/graph/FindCycles.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/graph/FindDependencies.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/graph/FindDuplicatedDependencies.kt
  tool/execution/parallel/src/main/kotlin/flank/exection/parallel/internal/graph/FindMissingDependencies.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/Example.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/ExecuteKtTest.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/ReduceKtTest.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/ValidateKtTest.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/benchmark/Execute.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/benchmark/Reduce.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/benchmark/Validate.kt
  tool/execution/parallel/src/test/kotlin/flank/exection/parallel/internal/graph/FindCyclesKtTest.kt
  tool/execution/synchronized/build.gradle.kts
Labels: Corellium

#2039 refactor: Data field should not be serialized
  test_runner/src/main/kotlin/ftl/args/CommonArgs.kt
Labels: P1, Styling, Tech Debt, Tiger 🐯

#2032 feat: Add structural logging
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InstallAndroidApps.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/InvokeAndroidDevices.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidApps.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidInstance.kt
  corellium/api/src/main/kotlin/flank/corellium/api/AndroidTestPlan.kt
  corellium/cli/build.gradle.kts
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/domain/build.gradle.kts
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Authorize.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CleanUpInstances.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/CreateOutputDir.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/DumpShards.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/Finish.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/GenerateReport.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InstallApks.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/InvokeDevices.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/LoadPreviousDurations.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseApkInfo.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ParseTestCases.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/PrepareShards.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/util/Transform.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumExample.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestMockApiAndroid.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/RunTestAndroidCorelliumTestParsingAndroid.kt
  tool/instrument/log/build.gradle.kts
  tool/junit/build.gradle.kts
  tool/log/src/main/kotlin/flank/log/Logger.kt
Labels: Corellium, Feature

#2042 feat: Send missing analytics data from Flank to Mixpanel
  docs/flank_mixpanel_metrics.md
  test_runner/src/main/kotlin/ftl/analytics/SendUsageStatistics.kt
  test_runner/src/main/kotlin/ftl/analytics/UsageStatisticsClient.kt
  test_runner/src/main/kotlin/ftl/client/google/AppDetails.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestAndroid.kt
  test_runner/src/main/kotlin/ftl/domain/RunTestIos.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/XcTestData.kt
  test_runner/src/main/kotlin/ftl/ios/xctest/common/Util.kt
  test_runner/src/main/kotlin/ftl/mock/MockServer.kt
  test_runner/src/main/kotlin/ftl/reports/CostReport.kt
  test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt
  test_runner/src/main/kotlin/ftl/run/platform/common/AfterRunTests.kt
  test_runner/src/main/kotlin/ftl/util/Billing.kt
  test_runner/src/test/kotlin/ftl/reports/utils/ReportManagerTest.kt
Labels: P0, Tiger 🐯

#2043 fix: Enhance table builder logic
  test_runner/src/main/kotlin/ftl/environment/TestEnvironmentInfo.kt
  test_runner/src/main/kotlin/ftl/environment/android/ListAndroidDevices.kt
  test_runner/src/main/kotlin/ftl/environment/ios/ListIOsDevices.kt
  test_runner/src/main/kotlin/ftl/environment/ios/ListIOsSofwareVersions.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/orientations/ListOrientations.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/android/versions/ListAndroidSofwareVersions.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/ipblocks/IpBlocksToTable.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/locale/ListLocales.kt
  test_runner/src/main/kotlin/ftl/presentation/cli/firebase/test/networkprofiles/ListNetworkConfiguration.kt
  test_runner/src/main/kotlin/ftl/util/LogTableBuilder.kt
  test_runner/src/test/kotlin/ftl/util/LogTableBuilderTest.kt
  test_runner/src/test/kotlin/ftl/util/TableColumnTest.kt
Labels: P2, Tech Debt, Tiger 🐯

#2047 feat: Implement slack notifications for failed release
  .github/workflows/create_new_release.yml
  .github/workflows/pr_checks.yml
  .github/workflows/release.yml
  .github/workflows/release_notes_generation.yml
Labels: Feature, Infrastructure, Tiger 🐯

#2050 fix: Corellium client request retry
  corellium/client/src/main/kotlin/flank/corellium/client/util/Retry.kt
  flank-scripts/build.gradle.kts
  flank-scripts/src/main/kotlin/flank/scripts/cli/assemble/FlankCommand.kt
  flank-scripts/src/main/kotlin/flank/scripts/ops/assemble/BuildFlank.kt
  flank-scripts/src/main/kotlin/flank/scripts/utils/GradleCommand.kt
Labels: Bug, Corellium, P0

#2049 feat: Save `am instrument` logs to file & handle parsing error.
  corellium/adapter/build.gradle.kts
  corellium/adapter/src/main/kotlin/flank/corellium/Api.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ClientReference.kt
  corellium/adapter/src/main/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlan.kt
  corellium/adapter/src/test/kotlin/flank/corellium/adapter/ExecuteAndroidTestPlanKtTest.kt
  corellium/api/src/main/kotlin/flank/corellium/api/CorelliumApi.kt
  corellium/cli/src/main/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommand.kt
  corellium/cli/src/test/kotlin/flank/corellium/cli/RunTestCorelliumAndroidCommandTest.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/RunTestCorelliumAndroid.kt
  corellium/domain/src/main/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTests.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/AdbLog.kt
  corellium/domain/src/test/kotlin/flank/corellium/domain/run/test/android/step/ExecuteTestsKtTest.kt
  docs/flank_corellium.md
Labels: Corellium, Feature
